In [1]:
import numpy as np
import pandas as pd

In [2]:
funding_2025 = pd.read_csv("indian_startup_funding_2020_2025_sample.csv")
funding_2015 = pd.read_csv("startup_funding.csv")

In [3]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [4]:
funding_2015.tail()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [5]:
funding_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [6]:
funding_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   object
 1   Industry              1100 non-null   object
 2   SubVertical           1100 non-null   object
 3   City                  1100 non-null   object
 4   Investors             1100 non-null   object
 5   InvestmentType        1100 non-null   object
 6   InvestmentAmount_USD  1100 non-null   int64
 7   Date                  1100 non-null   object
dtypes: int64(1), object(7)
memory usage: 68.9+ KB

In [7]:
funding_2015 = funding_2015.drop(['Sr No', 'Remarks'], axis=1)

In [8]:
funding_2015.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [9]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [10]:
funding_2015.rename(
    columns={
        "Date dd/mm/yyyy":'Date',
        'Startup Name':'Startup',
        'Industry Vertical':'Industry',
        'SubVertical':'Sub Vertical',
        'City  Location':'City',
        'Investors Name':'Investors',
        'InvestmentnType':'Investment Type',
        'Amount in USD': 'Investment Amount($)'},
    inplace=True)

In [11]:
funding_2015.columns

Index(['Date', 'Startup', 'Industry', 'Sub Vertical', 'City', 'Investors',
       'Investment Type', 'Investment Amount($)'],
      dtype='object')

In [12]:
funding_2025.rename(
    columns = {
        'InvestmentType':'Investment Type',
        'SubVertical':'Sub Vertical',
        'InvestmentnType':'Investment Type',
        'InvestmentAmount_USD':'Investment Amount($)'
        }, 
    inplace=True)

In [13]:
funding_2025.columns

Index(['Startup', 'Industry', 'Sub Vertical', 'City', 'Investors',
       'Investment Type', 'Investment Amount($)', 'Date'],
      dtype='object')

In [14]:
funding_2025['Date'] = pd.to_datetime(funding_2025['Date'])

C:\Users\hp\AppData\Local\Temp\ipykernel_6796\2638179884.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  funding_2025['Date'] = pd.to_datetime(funding_2025['Date'])

In [15]:
funding_2025.sort_values('Date', ascending=False, inplace=True)

In [16]:
funding_2025.head()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,2025-06-24

In [17]:
funding_2025.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1100 entries, 213 to 363
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   object
 1   Industry              1100 non-null   object
 2   Sub Vertical          1100 non-null   object
 3   City                  1100 non-null   object
 4   Investors             1100 non-null   object
 5   Investment Type       1100 non-null   object
 6   Investment Amount($)  1100 non-null   int64
 7   Date                  1100 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 77.3+ KB

In [18]:
test = pd.to_datetime(
    funding_2015['Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

funding_2015.loc[test.isna(), 'Date']

192               05/072018
2571              01/07/015
2606    \\xc2\\xa010/7/2015
3029            22/01//2015
Name: Date, dtype: object

In [19]:
funding_2015['Date'] = funding_2015['Date'].str.replace('05/072018','05/07/2018')
funding_2015['Date'] = funding_2015['Date'].str.replace('01/07/015','01/07/2015')
funding_2015['Date'] = funding_2015['Date'].str.replace(r'\\xc2\\xa010/7/2015', '10/07/2015', regex=False)
funding_2015['Date'] = funding_2015['Date'].str.replace(r'22/01//2015', '22/01/2015')

In [20]:
funding_2015['Date'] = pd.to_datetime(funding_2015['Date'], format='mixed')

In [21]:
funding_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  3044 non-null   datetime64[ns]
 1   Startup               3044 non-null   object
 2   Industry              2873 non-null   object
 3   Sub Vertical          2108 non-null   object
 4   City                  2864 non-null   object
 5   Investors             3020 non-null   object
 6   Investment Type       3040 non-null   object
 7   Investment Amount($)  2084 non-null   object
dtypes: datetime64[ns](1), object(7)
memory usage: 190.4+ KB

In [22]:
funding = pd.concat([funding_2025, funding_2015])

In [23]:
funding.head()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,2025-06-24

In [24]:
funding.tail()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
3039,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",2015-01-29
3040,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",2015-01-29
3041,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",2015-01-30
3042,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,2015-01-30
3043,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",2015-01-31

In [25]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4140 non-null   object
 6   Investment Amount($)  3184 non-null   object
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 291.4+ KB

In [26]:
funding['Startup'].nunique()

2605

## Handle Investment Amount($) colomn

In [27]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna('unknown')
funding['Investment Amount($)']

213        168000
923      45929000
842         96000
236        141000
957         59000
          ...
3039    45,00,000
3040     8,25,000
3041    15,00,000
3042      unknown
3043     1,40,000
Name: Investment Amount($), Length: 4144, dtype: object

In [28]:
# Remove commas(,)
funding['Investment Amount($)'].astype('string') + ','
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('string').str.replace(',', '', regex=False)

In [29]:
funding['Investment Amount($)']

213       168000
923     45929000
842        96000
236       141000
957        59000
          ...
3039     4500000
3040      825000
3041     1500000
3042     unknown
3043      140000
Name: Investment Amount($), Length: 4144, dtype: string

In [30]:
funding['Investment Amount($)'][funding['Investment Amount($)'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Investment Amount($)
unknown               961
\\xc2\\xa0N/A           4
undisclosed             3
Undisclosed             3
\\xc2\\xa020000000      1
\\xc2\\xa016200000      1
\\xc2\\xa0600000        1
\\xc2\\xa0685000        1
\\xc2\\xa019350000      1
\\xc2\\xa05000000       1
\\xc2\\xa010000000      1
Name: count, dtype: Int64

In [31]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].str.replace(r'\\xc2\\xa0','')

In [32]:
funding['Investment Amount($)'] = pd.to_numeric(funding['Investment Amount($)'], errors='coerce')

funding['Investment Amount($)'].isna().sum()

np.int64(972)

In [33]:
check = funding.groupby('Startup').agg(
    Total_Rows=('Investment Amount($)', 'size'),
    NaN_Amount=('Investment Amount($)', 'count')
)

check['NaN_Amount'] = check['Total_Rows'] - check['NaN_Amount']

nan_values = check[check['Total_Rows'] == 1]

nan_values['NaN_Amount'].sum()

np.int64(705)

In [34]:
fill = funding.groupby('Startup')['Investment Amount($)'].transform('mean')
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna(fill)
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna(funding['Investment Amount($)'].mean())

In [35]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('string')
funding['Investment Amount($)'][funding['Investment Amount($)'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Series([], Name: count, dtype: Int64)

In [36]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('float')

In [37]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4140 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

In [38]:
funding['Investment Amount($)'].isna().sum()

np.int64(0)

## Handle Investment Type colomn

In [39]:
funding['Investment Type'].isna().sum()

np.int64(4)

In [40]:
# funding['Investment Type'].value_counts()

In [41]:
funding['Investment Type'].unique()

array(['Pre-Series A', 'Series B', 'Seed', 'Bridge', 'Series A', 'Angel',
       'Series D', 'Series C', 'Debt', 'Growth', 'Pre-Seed',
       'Private Equity', 'Private Equity Round', 'Pre-series A',
       'Seed Round', 'Series F', 'Series E', 'Debt Funding', 'Series G',
       'Series H', 'Venture', 'Seed Funding', nan, 'Funding Round',
       'Corporate Round', 'Maiden Round', 'pre-series A',
       'Seed Funding Round', 'Single Venture', 'Venture Round',
       'Series J', 'Angel Round', 'pre-Series A',
       'Venture - Series Unknown', 'Bridge Round',
       'Debt and Preference capital', 'Inhouse Funding',
       'Seed/ Angel Funding', 'Pre Series A', 'Equity', 'Debt-Funding',
       'Mezzanine', 'Series B (Extension)', 'Equity Based Funding',
       'Private Funding', 'Seed / Angel Funding', 'Seed/Angel Funding',
       'Seed funding', 'Seed / Angle Funding', 'Angel / Seed Funding',
       'Private', 'Structured Debt', 'Term Loan', 'PrivateEquity',
       'Angel Funding', 'Seed\\\\nFunding', 'Private\\\\nEquity',
       'Crowd funding', 'Crowd Funding'], dtype=object)

In [42]:
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Venture - Series Unknown','Venture - Series')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed/ Angel Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed / Angle Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed/Angel Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Angel / Seed Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed\\nFunding','Seed Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Private\\nEquity','Private Equity')

In [43]:
fill = funding.groupby('Startup')['Investment Type'].transform(
    lambda x: x.mode().iloc[0] if not x.mode().empty else 'Not Know'
)

funding['Investment Type'] = funding['Investment Type'].fillna(fill)

In [44]:
funding['Investment Type'].isna().sum()

np.int64(0)

In [45]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Handle Investors colomn

In [46]:
funding['Investors'].value_counts()

Investors
Kalaari Capital                               42
Undisclosed Investors                         39
Y Combinator                                  31
Info Edge                                     31
Undisclosed investors                         30
                                              ..
Fairfax Holdings                               1
Tekne Capital Management LLC                   1
Sequoia India, NEA, Prime Venture Partners     1
Nexus Venture Partners, Mekin Maheshwari       1
UK based Group of Angel Investors              1
Name: count, Length: 2818, dtype: int64

In [47]:
funding['Investors'].nunique()

2818

In [48]:
funding.loc[funding['Investors'].isna()]

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
13,InCred,Finance,Non-Banking Financial Company,Mumbai,NaN,Debt Funding,5.900000e+06,2019-12-16
46,MyPetrolPump,Retail,Fuel Delivery,Bengaluru,NaN,Seed Funding Round,1.600000e+06,2019-01-08
154,3HCare,Healthcare,Healthcare Service Provider,Delhi,NaN,Seed / Angel Funding,1.000000e+06,2018-04-09
168,My OmNamo,Consumer Internet,Holy Platform Offering Customised Puja Package...,Mumbai,NaN,Seed / Angel Funding,1.000000e+06,2018-07-08
178,Enakshi,Consumer Internet,AI Based Solutions Platform,Ahemadabad,NaN,Seed / Angel Funding,1.148110e+05,2018-08-16
180,Finzy,Finance,Online Loan Matchmaking Platform,Bengaluru,NaN,Seed / Angel Funding,1.000000e+06,2018-08-20
188,True North,Finance,Private Equity Firm,Mumbai,NaN,Private Equity,6.000000e+08,2018-08-30
208,HousingMan,Consumer Internet,Property Discovery Platform,Bengaluru,NaN,Seed / Angel Funding,1.500000e+06,2018-07-20
210,Yulu Bikes,Technology,Bicycle-Sharing Platform,Bengaluru,NaN,Seed / Angel Funding,2.077046e+07,2018-07-23
260,PaisaDukan,Consumer Internet,P2P Lending Platform,Mumbai,NaN,Seed / Angel Funding,2.250000e+05,2018-07-05
283,Finzy,Consumer Internet,Online Loan Matchmaking Platform,Bengaluru,NaN,Seed / Angel Funding,1.300000e+06,2018-02-04
290,Kriger Campus,Ed-Tech,Mobile-Based Education Network,Delhi,NaN,Seed / Angel Funding,4.614000e+04,2018-09-04
306,Mihuru,Finance,Online Platform Providing Micro Loans For Air ...,Mumbai,NaN,Seed / Angel Funding,1.500000e+05,2018-04-23
345,Roadcast,Technology,Fleet management and asset monitoring platform,Delhi,NaN,Private Equity,2.500000e+05,2018-03-28
396,Kinsane Entertainment Inc,Entertainment,Digital Entertainment for Children,Mumbai,NaN,Seed / Angel Funding,2.500000e+06,2018-09-01
458,Cash Suvidha,E-Commerce,Online Micro-Lending Platform,Delhi,NaN,Debt Funding,2.700000e+06,2017-12-15
684,MyCity4kids,Consumer Internet,parenting blog and kids\\xe2\\x80\\x99 events ...,Gurgaon,NaN,Seed Funding,2.077046e+07,2017-06-07
843,Cube Consumer Services,Consumer Internet,Finance management Mobile app,Mumbai,NaN,Seed Funding,2.077046e+07,2017-05-29
2113,Zapluk,"Health, Wellness & Beauty Services App",NaN,Hyderabad,NaN,Seed Funding,2.077046e+07,2015-01-12
2204,LoanBaba,Online Loans Marketplace,NaN,Mumbai,NaN,Seed Funding,3.200000e+05,2015-03-11
2278,JustRide,Self Driven Rental Car Platform,NaN,Mumbai,NaN,Private Equity,2.000000e+06,2015-11-27
2408,Zapyle,pre-used apparel shopping mobile app,NaN,Bangalore,NaN,Seed Funding,1.000000e+06,2015-11-09
2690,kWatt Solutions,Renewable energy solutions,NaN,Mumbai,NaN,Seed Funding,5.000000e+05,2015-05-06
2812,KeepTrax,Location Based App,NaN,Dallas / Hyderabad,NaN,Seed Funding,1.000000e+06,2015-04-04

In [49]:
funding['Investors'] = funding['Investors'].fillna('Unknown')

In [50]:
funding['Investors'].isna().sum()

np.int64(0)

In [85]:
funding['Investors'].nunique()

2819

In [86]:
# Find Invalid name
funding['Investors'][funding['Investors'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Investors
Kalaari Capital                               42
Undisclosed Investors                         39
Info Edge                                     31
Y Combinator                                  31
Blume Ventures                                30
                                              ..
Fairfax Holdings                               1
Tekne Capital Management LLC                   1
Sequoia India, NEA, Prime Venture Partners     1
Nexus Venture Partners, Mekin Maheshwari       1
UK based Group of Angel Investors              1
Name: count, Length: 2819, dtype: int64

In [52]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Handle City colomn

In [53]:
funding['City'].isnull().sum()

np.int64(180)

In [54]:
funding['City'].value_counts()

City
Bangalore             700
Mumbai                671
New Delhi             421
Gurgaon               287
Bengaluru             248
                     ...
Delhi & Cambridge       1
Bhubneswar              1
Srinagar                1
Rourkela                1
Dallas / Hyderabad      1
Name: count, Length: 112, dtype: int64

In [55]:
funding['City'].unique()

array(['Noida', 'Pune', 'Mumbai', 'Delhi', 'Ahmedabad', 'Gurugram',
       'Kolkata', 'Bengaluru', 'Hyderabad', 'Chennai', 'Gurgaon',
       'New Delhi', 'Faridabad', 'San Francisco', 'San Jose,', 'Amritsar',
       'Kormangala', 'Tulangan', 'Burnsville', 'Menlo Park', 'Palo Alto',
       'Santa Monica', 'Singapore', 'Taramani', 'Andheri', 'Chembur',
       'Nairobi', 'Haryana', 'New York', 'Karnataka', 'Mumbai/Bengaluru',
       'Bhopal', 'Bengaluru and Gurugram', 'India/Singapore', 'Jaipur',
       'India/US', 'Nagpur', 'Indore', 'New York, Bengaluru',
       'California', 'India', 'Ahemadabad', 'Rourkela', 'Srinagar',
       'Bhubneswar', 'Chandigarh', 'Delhi & Cambridge', 'Kolkatta',
       'Coimbatore', 'Bangalore', 'Udaipur', nan, 'Ahemdabad',
       'Bhubaneswar', 'Surat', 'Goa', 'Uttar Pradesh', 'Nw Delhi', 'Gaya',
       'Vadodara', 'Trivandrum', 'Missourie', 'Panaji', 'Gwalior',
       'Karur', 'Udupi', 'Kochi', 'Agra', 'Bangalore/ Bangkok', 'Hubli',
       'Kerala', 'Kozhikode', 'US', 'Siliguri', 'USA', 'Lucknow',
       'Kanpur', 'SFO / Bangalore', 'London', 'Seattle / Bangalore',
       'Pune/Seattle', 'Pune / Dubai', 'Bangalore / SFO', 'Varanasi',
       'New Delhi / US', 'Mumbai / UK', 'Jodhpur', 'Hyderabad/USA',
       'Boston', 'Bangalore / Palo Alto', 'Mumbai / NY', 'USA/India',
       'Goa/Hyderabad', 'Noida / Singapore', 'Belgaum', 'Pune / US',
       'Chennai/ Singapore', 'Pune / Singapore', 'Bangalore / San Mateo',
       'New York/ India', 'US/India', 'Gurgaon / SFO', 'Bangalore / USA',
       'New Delhi/ Houston', 'Mumbai / Global', 'India / US',
       '\\\\xc2\\\\xa0Noida', '\\\\xc2\\\\xa0Bangalore',
       '\\\\xc2\\\\xa0Gurgaon', '\\\\xc2\\\\xa0New Delhi',
       '\\\\xc2\\\\xa0Mumbai', 'New Delhi / California',
       'Dallas / Hyderabad'], dtype=object)

In [61]:
funding['City'] = (
    funding['City']
    .str.replace(r'\\\\xc2\\\\xa0', '', regex=True)
    .str.strip()
)

funding['City'] = funding['City'].replace({
    'Gurgaon': 'Gurugram',
    'New Delhi': 'Delhi',
    'Nw Delhi': 'Delhi',
    'Bangalore': 'Bengaluru',
    'Kormangala': 'Bengaluru',
    'Ahemadabad': 'Ahmedabad',
    'Ahemdabad': 'Ahmedabad',
    'Bhubneswar': 'Bhubaneswar',
    'Kolkatta': 'Kolkata',
    'Taramani': 'Chennai',
    'Andheri': 'Mumbai',
    'Chembur': 'Mumbai',
    'Haryana': 'Gurugram',
    'Karnataka': 'Bengaluru',
    'Uttar Pradesh': 'Noida',
    'Kerala': 'Kochi',
    'Panaji': 'Goa',
    'San Jose,': 'San Jose',
    'US': 'United States',
    'USA': 'United States',
})

funding['City'].value_counts()

City
Bengaluru              952
Mumbai                 674
Delhi                  587
Gurugram               451
Pune                   218
                      ...
Tulangan                 1
SFO / Bangalore          1
London                   1
Seattle / Bangalore      1
Dallas / Hyderabad       1
Name: count, Length: 89, dtype: int64

In [62]:
funding['City'].unique()

array(['Noida', 'Pune', 'Mumbai', 'Delhi', 'Ahmedabad', 'Gurugram',
       'Kolkata', 'Bengaluru', 'Hyderabad', 'Chennai', 'Faridabad',
       'San Francisco', 'San Jose', 'Amritsar', 'Tulangan', 'Burnsville',
       'Menlo Park', 'Palo Alto', 'Santa Monica', 'Singapore', 'Nairobi',
       'New York', 'Mumbai/Bengaluru', 'Bhopal', 'Bengaluru and Gurugram',
       'India/Singapore', 'Jaipur', 'India/US', 'Nagpur', 'Indore',
       'New York, Bengaluru', 'California', 'India', 'Rourkela',
       'Srinagar', 'Bhubaneswar', 'Chandigarh', 'Delhi & Cambridge',
       'Coimbatore', 'Udaipur', nan, 'Surat', 'Goa', 'Gaya', 'Vadodara',
       'Trivandrum', 'Missourie', 'Gwalior', 'Karur', 'Udupi', 'Kochi',
       'Agra', 'Bangalore/ Bangkok', 'Hubli', 'Kozhikode',
       'United States', 'Siliguri', 'Lucknow', 'Kanpur',
       'SFO / Bangalore', 'London', 'Seattle / Bangalore', 'Pune/Seattle',
       'Pune / Dubai', 'Bangalore / SFO', 'Varanasi', 'New Delhi / US',
       'Mumbai / UK', 'Jodhpur', 'Hyderabad/USA', 'Boston',
       'Bangalore / Palo Alto', 'Mumbai / NY', 'USA/India',
       'Goa/Hyderabad', 'Noida / Singapore', 'Belgaum', 'Pune / US',
       'Chennai/ Singapore', 'Pune / Singapore', 'Bangalore / San Mateo',
       'New York/ India', 'US/India', 'Gurgaon / SFO', 'Bangalore / USA',
       'New Delhi/ Houston', 'Mumbai / Global', 'India / US',
       'New Delhi / California', 'Dallas / Hyderabad'], dtype=object)

In [64]:
funding['City'] = funding['City'].fillna('Unknown')

In [65]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  4144 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Handle Sub Vertical column

In [82]:
funding['Sub Vertical'].value_counts()

Sub Vertical
Fashion                                       67
Grocery                                       67
Supply Chain                                  52
Marketplace                                   45
Food Delivery                                 35
                                              ..
Beauty products discovery platform             1
Tech driven Insurance platform                 1
CSR and sustainability management platform     1
Location tracking solutions                    1
Interior Design Marketplace                    1
Name: count, Length: 1983, dtype: int64

In [92]:
funding['Sub Vertical'].nunique()

1984

In [93]:
funding['Sub Vertical'] = funding['Sub Vertical'].fillna('Unknown')

In [94]:
# Find Invalid name
funding['Sub Vertical'][funding['Sub Vertical'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Sub Vertical
Unknown                                       936
Grocery                                        67
Fashion                                        67
Supply Chain                                   52
Marketplace                                    45
                                             ...
Beauty products discovery platform              1
Tech driven Insurance platform                  1
CSR and sustainability management platform      1
Location tracking solutions                     1
Online freight aggregator                       1
Name: count, Length: 1984, dtype: int64

In [95]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          4144 non-null   object
 3   City                  4144 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Handle Industry colum

In [97]:
funding['Industry'].value_counts()

Industry
Consumer Internet                       941
Technology                              478
eCommerce                               186
E-commerce                              102
Retail                                   90
                                       ...
Music Streaming mobile app                1
Raw Meat & Ready to eat food etailer      1
Gym Discovery platform                    1
Online Purchase rewards app               1
Online Travel Marketplace                 1
Name: count, Length: 828, dtype: int64

In [99]:
funding['Industry'].unique()

array(['AgriTech', 'EdTech', 'HealthTech', 'Retail', 'SaaS', 'Logistics',
       'Mobility', 'E-commerce', 'RealEstate', 'FoodTech', 'Enterprise',
       'FinTech', 'Consumer Electronics', 'Media', 'E-Tech',
       'Transportation', 'Fashion and Apparel', 'Hospitality',
       'Technology', 'E-Commerce', 'Aerospace',
       'B2B-focused foodtech startup', 'Finance', 'Video', 'Gaming',
       'Software', 'Health and wellness', 'Education',
       'Food and Beverage', 'Health and Wellness', 'B2B Marketing',
       'Video Games', 'Last Mile Transportation', 'Healthcare',
       'Customer Service', 'B2B', 'Consumer Goods',
       'Advertising, Marketing', 'IoT', 'Information Technology',
       'Consumer Technology', 'Accounting', 'Customer Service Platform',
       'Automotive', 'Services', 'Compliance', 'Transport',
       'Artificial Intelligence', 'Tech', 'Health Care', 'Luxury Label',
       'Waste Management Service', 'Deep-Tech', 'Agriculture', 'Energy',
       'Digital Media', 'Saas', 'Automobile', 'Agtech', 'Social Media',
       'Fintech', 'Edtech', 'AI', 'Ecommerce', 'Nanotechnology',
       'Services Platform', 'Travel Tech', 'Online Education',
       'Online Marketplace', 'SaaS, Ecommerce', 'NBFC', 'Food',
       'Food Tech', 'Automation', 'Investment', 'Social Network',
       'Financial Tech', 'Fashion', 'Real Estate', 'Logistics Tech',
       'Consumer Internet', 'B2B Platform', 'Fin-Tech', 'Food-Tech',
       'Ed-Tech', 'IT', 'Ed-tech', 'Clean-tech', 'Fiinance',
       'Food & Beverages', 'Food and Beverages', 'Publishing',
       'Entertainment', 'Consumer internet', 'ECommerce', 'eCommerce',
       'Inspiration', 'Storytelling', 'Lifestyle', 'Food & Beverage',
       'eCommece', 'Consumer Portal', 'Others', 'ecommerce', 'healthcare',
       'FMCG', 'Reality', 'Auto', 'BFSI', 'Consumer Interne',
       'Online Education Information platform', 'Brand Licensing Startup',
       'Gourmet Food Discovery & Delivery platform',
       'Transportation & Logistics Platform',
       'Enterprise Marketing Automation platform',
       'Health, Wellness & Beauty Services App', 'Digital Healthcare',
       'Last Minute Hotel Booking App', 'Womens Fashion Wear Portal',
       'Product Learning platform',
       'Online Food ordering & Delivery platform',
       'App based Bus Pooling Services', 'Social Learning Platform',
       'Social Fitness platform', 'On Demand Mobile app developer',
       'Car Maintenance & Management mobile app',
       'Online Wedding Marketplace', 'Splitting Bills Mobile App',
       'IOT Energy Management Analytics platform',
       'Custom Made furniture e-tailer', 'QSR Chain',
       'eLearning platform', 'Smart Safety Wearable Devices',
       'Cab Sharing service Mobile app',
       'Cloud Enterprise Mobility Platform',
       'Online Shopping Assistant Mobile app',
       'Home Cooked Food Order & Delivery platform',
       'Online School for Analytics learning',
       'Chat based personal Assistant App',
       'Picture creation & Social mobile app',
       'Nonbanking finance company', 'eCommerce returns etailer',
       'Online Freight Services Aggregator',
       'Online Branded Furniture etailer', 'Digital Analytics Platform',
       'Internet Network Infrastructure Services',
       'Supply Chain & Logistics Solutions', 'Holiday Resort Chain',
       'Mobile Point of Sale solutions',
       'Peer-to-Peer Money Transfer & Recharge App',
       'Test Automation SAAS platform', 'Citizens Engagement Platform',
       'Indoor Navigation & Analytics Solutions',
       'Hyperlocal On-Demand Household Services platform',
       'Online RTI application services',
       'ECommerce Website Creation SAAS platform',
       'Wedding Venues & Vendors Marketplace',
       'Interface development platform for Government officials',
       'Modular Furnishings Marketplace',
       'Private Jet Bookings Marketplace',
       'Cab search Comparison & Booking platform',
       'Performance Optimization Platform for athletes',
       'Event Venue Booking Platform', 'Digital Media Platform',
       'visual search and discovery platform',
       'Home services marketplace',
       'End to End reverse logistics Solution platform',
       'Virtual Health consultation app', 'Online Renting platform',
       'Logistics Services Provider',
       'Data Science & UX design Learning platform',
       'Online marketplace for Chef Meals', 'Electric Bike Manufacturers',
       'ECommerce platform solutions', 'Online Media Publication',
       'International Hiring Platform',
       'Logistics Service Provider Marketplace',
       'Hyperlocal\\\\xc2\\\\xa0 Grocery Delivery Service',
       'Sports Education Platform',
       'Bike, Appliances Renting marketplace',
       'Online Marketplace for Industrial Goods',
       'Reward points mobile app', 'Mobile accessories online store',
       'Content Discovery & reward points platform',
       'Artificial Intelligence platform',
       'Medical Consultation & Doctor appointment booking platform',
       'Mobile Fitness App',
       'Digital Coupons, Deal & Cashback aggregator app',
       'Mobile Game development & Design platform',
       'B2B eCommerce Marketplace',
       'Furniture and appliances rental platform',
       'B2B Merchandize platform', 'Real Estate focused Tech platform',
       'Photographer Online search & booking platform',
       'Grocery Delivery platform',
       'Mobile Car Servicing appointment app', 'New Curation Mobile App',
       'Mobile Wallet', 'Online Food Ordering & Delivery platform',
       'Bus Aggregation and rental mobile app',
       'hyperlocal online Services platform',
       'WiFi \\xe2\\x80\\x93 first Cloud communication platform',
       'Alternate Mobile Monetization platform',
       'Online Food Ordering Marketplace',
       'Quick Service Restaurant & Online Delivery',
       'Online Loans Marketplace', 'Budget Hotels Aggregator',
       'Efficient Energy Management platform',
       'Digital Intelligent learning platform',
       'Voice Call incentivization mobile app',
       'Online Counselling and psychological support platform',
       'Domestic Help Aggregation platform',
       'Home Stay & room rentals platform', 'Selfie Mobile App',
       'Online Reputation Management Platform', 'Online Grocery platform',
       'Online content platform for women',
       'Online Vehicle Spare Parts etailer', 'Event Ticketing platform',
       'affordable Personal Healthcare Products',
       'Premium dining Lounges & restaurants',
       'Mobile Growth Hacking\\\\nPlatform', 'Skill Training Startup',
       'Beauty and Wellness Marketplace', 'Marketplace App for Bangkok',
       'On-demand Maids Service Provider',
       'eCommerce Product Search Engine', 'Ready to cook packaged Foods',
       'Product Customization Platform',
       'Branded Food products online sales',
       'Talent platform for Fashion professionals',
       'Auto Insurance Online platform',
       'Hyperlocal Logistics Service Provider',
       'Cricket Management Mobile Game',
       'On Demand Laundry Service platform',
       'Ecommerce Discount & Cashback coupons platform',
       'Virtual Reality Headset creator',
       'Home Improvement Service platform',
       'mobile-only tasks marketplace',
       'Women Ethnic Wear\\\\xc2\\\\xa0 Online Marketplace',
       'Numerical Computing & Data Science Platform',
       'Designer fashion Jewellery Marketplace',
       'Online Products Discovery Platform',
       'Kids Tool kit for Innovation platform',
       'Mobile Learning Solutions', 'Car Aggregator & Retail Mobile App',
       'conversational commerce mobile app', 'Viral Content web Platform',
       'Express local delivery platform',
       'On-Demand Local Logistics provider',
       'Curated Freelancer Marketplace', 'Online Taxi Rental Platform',
       'Mobile Services Marketplace', 'Smartwatch Maker',
       'Online Gourmet Food Marketplace', 'Online Jewellery etailer',
       'Sales & Productivity Software',
       'ecommerce related software product platform',
       'Health-Tech platform', 'Nightlife Discovery Mobile App',
       'Online Real Estate Marketplace',
       'Home Healthcare Services platform,',
       'Indian Ethnic Crafts Etailer',
       'Social platform for traders and investors',
       'Online Furniture, Home Appliances Rental Platform',
       'Healthcare Services Discovery platform',
       'Health and Beauty Services Marketplace',
       'Automotive Services platform',
       'Online and TV Shopping Marketplace',
       'Big Data Analytics Platform',
       'Mobile App based Loan disbursement platform',
       'On Demand Laundry Services App', 'Education Content Provider',
       'Content Management Software Solutions',
       'Fitness Tracking Management Solutions',
       'Hyper-local Grocery Delivery platform',
       'Hyperlocal healthcare product Delivery Service provider',
       'Online Lending Marketplace', 'On Demand Beauty Services Platform',
       'Self Driven Rental Car Platform', 'Education Content etailer',
       'Clud based Learning platform',
       'Talent Exchange & Talent Services Marketplace',
       'Two-Wheeler Taxi Service', 'character merchandize sales platform',
       'Mobile Application Developer',
       'Ecommerce Delivery locker services',
       'extra curricular activities marketplace app',
       'Hyperlocal Online Home services provider',
       'Easy Business Loans platform',
       'Performance based Wholesale Marketplace',
       'Professional Services Marketplace', 'Movie-on-demand platform',
       'us ticketing and fleet management platform',
       'Online Income Tax Filing platform',
       'Product discovery & recommendation platform',
       'Mobile Payments App', 'Beauty & Wellness Products e-tailer',
       'Fashion jewelry and accessories e-tailer',
       'Online Consumer Lending platform',
       'Premium Apparel shopping portal',
       'Exclusive Platform for Doctors & Healthcare professionals',
       'Job Board', 'Sports Management & Physical Education Business',
       'multi-sport program for preschoolers',
       'QSR & Online delivery portal', 'Online Homeopathy Clinic',
       'E-Learning Service Provider', 'Organic Food etailer',
       'Delivery & Logistics Service provider',
       'Product Discovery & comparison App',
       'Online Apparels Fashion brand',
       'Home Cooked Food marketplace & Delivery',
       'Gesture based Mobile Development',
       'Hotel Mobile CRM Software platform',
       'Rental Accommodation Search platform', 'Logistics Tech Platform',
       'Developer Portfolio Showcase platform',
       'Doctors Network Mobile App', 'End-to-End Lending platform',
       'on-demand healthcare marketplace',
       '360-degree view creating platform',
       'Advertising & Marketing Community Networking platform',
       'Food Ordering & Delivery App', 'Ride Sharing platform',
       'Online P2P lending marketplace',
       'B2B marketplace for industrial goods',
       'Cloud Based Collaboration platform',
       'global community for travellers', 'Prepaid Bill manager App',
       'Mobile Only Shopping Assistant', 'Mobile Messaging Assistant App',
       'Personalized Wish List creator app', 'Music Streaming mobile app',
       'Raw Meat & Ready to eat food etailer', 'Gym Discovery platform',
       'Online Purchase rewards app', 'Home rental platform',
       'Crowdsourced Delivery platform', 'Real Estate Insights platform',
       'Structural & Civil Engg Service Automation',
       'Startup Funding Marketplace', 'Payments Solution platform',
       'Travel Destination Discovery platform',
       'Order Fulfillment SAAS platform', 'Last Mile Delivery Service',
       'Healthcare IT Solutions & services', 'Gourmet Meals Delivery',
       'Healthy Meals Food delivery platform', 'Real Estate Mobile CRM',
       'Micro-Brewery', 'Home Made Food Marketplace',
       'residential rental management platform',
       'Personalized Stock Intelligence Platform',
       'Personal Diagnostic Mobile App',
       'Online food ordering & Delivery service',
       'Hotel Aggregator & booking platform', 'Online Logistics Platform',
       'Online Student & Campus Social Networking platform',
       'Professionals & Project Search Marketplace', 'Online Pharmacy',
       'Online Payment Gateway', 'Psychometric Test Online Software',
       'Location based Nightlife recommendation\\\\xc2\\\\xa0 Platform',
       'Professional Health Services Platform',
       'Hyperlocal Logistics Service', 'Online user engagement platform',
       'Asset Financing platform',
       'Virtual Reality activity based learning platform',
       'Online Grocery Store', 'Investment management platform',
       'Industrial Toons Marketplace', 'Public Commute helper App',
       'Artificial Intelligence Ecommerce Chatbot',
       'Truck Aggregator & Logistics service', 'Ridesharing Mobile app',
       'Food Discovery & Delivery Mobile app',
       'Competitive exam learning platform',
       'Document Digitization platform',
       'proximity marketing & Mobile Advertising platform',
       'Autorickshaw Aggregator & Booking platform',
       'FinTech Startup Incubation platform', 'Payment Services platform',
       'Personalized Styling platform',
       'Luxury goods\\\\xc2\\\\xa0 Shopping Platform',
       'Food Delivery Platform', 'Online Lingerie Marketplace',
       'Cloud software solutions', 'Job Search Platform',
       'Doctor consultancy Mobile App', 'Small Business Financing (NBFC)',
       'Beauty & Wellness Services Marketplace',
       'Online Movie Review Platform',
       'ECommerce Brands\\\\xe2\\\\x80\\\\x99 Full Service Agency',
       'Cloud-based Hotel Booking Platform',
       'Community Driven News/Views Platform',
       'Study Material Marketplace',
       'Restaurant Ratings & Reviews platform',
       'Dairy Based Product Manufacturer',
       'Government Test Preparation platform',
       'Smart Report Cards for Schools', 'Teacher empowerment platform',
       'Multilingual Test Preparation Platform',
       'Industrial Tools Marketplace',
       'Non Profit Organization to alleviate poverty',
       'Gym & Fitness Studios Subscription platform',
       'pre-used luxury item Marketplace',
       'pre-used apparel shopping mobile app',
       'Home Design & D\\\\xc3\\\\xa9cor platform',
       'Used Vehicles Marketplace', 'Online Bus & Cab ticketing platform',
       'Mobile App testing platform', 'Hyperlocal Delivery Services',
       'Early Cancer Detection Solutions', 'Cab rental Mobile app',
       'Online Insurance Distribution Platform',
       'Mobile Marketing Automation Platform',
       'Prepaid Mobile Bill Manager App',
       'Chain of Tea Caf\\\\xc3\\\\xa9\\\\xe2\\\\x80\\\\x99s',
       'Branded Budget Hotel Marketplace',
       'Home Fitting & Fixtures Marketplace',
       'Food Subscription platform', 'Wedding Planning Platform',
       'B2B Mobile Auction Marketplace',
       'ECommerce Data Analytics Platform',
       'Designer Merchandize Marketplace',
       'Private label Fashion eTailer', 'Online Food ordering & delivery',
       'Real Estate Broker Platform App',
       'Online Health & Wellness platform', 'Internet of Things platform',
       'Diagnostic Labs aggregator platform',
       'Hyperlocal Delivery Platform', 'Home Medical Care Services',
       'Real-Time stock data platform',
       'Food discovery & table booking app',
       'coupons and cashback aggregator app',
       'Financial Products lead generation platform',
       'Sustainable Agri-inputs Firm', 'Financial Services Portal',
       'Pre-owned games Marketplace',
       'Content-based Subscription eCommerce platform',
       'virtual reality, 3d simulation and stereoscopic products',
       'Online Interior Designing platform',
       'End-to-end Logistics platform', 'Private Label Apparel sales',
       'Healthcare Consulting platform', 'Stock Market Portal',
       'Cross-device retargeting platform',
       'Digital & Physical Publishing platform',
       'Data Driven Publishing platform',
       'Employee OnBoarding & Orientation platform',
       'Solar Power Solutions company', 'Online Meat Ordering platform',
       'online meal-booking platform for train travelers',
       'hyperlocal delivery platform', 'Cab Booking app platform',
       'E-Commerce & M-Commerce platform', 'Mobile Advertising platform',
       'Hyperlocal Grocery Delivery',
       'Ecommerce Product recommendation platform',
       'Activity Based Social Network', 'Fashion Discovery platform',
       'Consumer lending marketplace', 'Big Data Management Platform',
       'Budget Accommodation Platform', 'Local Mobile OS',
       'Digital Signal processing platform', 'Ecommerce Marketplace',
       'Restaurant Discount app', 'Tech-enabled learning',
       'ECommerce Logistics provider',
       'on-demand home beauty and wellness portal',
       'Self Driven Car rental', 'Budget Hotel accommodation brand',
       'Energy & Environment Online Marketplace',
       'User Engagment & Analytics platform',
       'On-Demand Delivery Logistics',
       'fund raising platform for startups', 'Online budget hotel chain',
       'Hyperlocal Handyman services', 'hotel booking app',
       'Rental Accomodation finder', 'Tech Platform for property brokers',
       'Luxury Apparel rental',
       'App security\\\\xc2\\\\xa0 testing platform',
       'Doctor Appointment booking app', 'anonymous bulletin board app',
       'Travel community platform', 'Crowd funding platform',
       'Mobile based PoS solution', 'Car & Bike ecommerce platform',
       'Fast food Chain Franchisee', 'Loyalty Programs & Reward Points',
       'Energy saving solutions provider', 'Self-Storage Spaces',
       'Grocery retail Mobile app', 'Taxi Rental platform',
       'Machine Learning Platform', 'mobile social network',
       'Hyper-Local Ecommerce', 'Online printing marketplace',
       'mobile payment software platform',
       'Automated Storage & Warehousing Solution',
       'Home Design & D\\\\xc3\\\\xa9cor solutions',
       'Quick Service Restaurant Chain',
       'Subscription based Online Grocery platform',
       'engineering services company', 'Business and IT consulting',
       'Credit Card Fraud protection solutions',
       'Online & mobile Grocery store', 'Career Community for Women',
       'Mutual Fund Investing platform',
       'Ecommerce Marketing Software Platform',
       'Financial Inclusion platform',
       'Digital Marketing automation solution',
       'Mobile Commerce for Farmers', 'Picture based Social App',
       'Logistics service platform', 'On-Demand Beauty Services',
       'Exam Preparation Platform', 'Startup Focused Online Publisher',
       'Waste Management Solutions', 'App based Fitness coaching',
       'On demand cleaning & fixing services',
       'Beauty & Lifestyle platform', 'on-demand delivery service',
       'Data Analytics Platform', 'Deep Learning Cloud Algorithms',
       'Location based engagement & rewards platform',
       'Online Identity Verification Services platform',
       'Corporate Wellness App', 'Fashion Search & Review Platform',
       'Hyperlocal Maintenance, Repair & Cleaning services',
       'pre-owned Luxury online apparel seller',
       'Online Furniture Marketplace',
       'Online Diagnostic Tests Marketplace',
       'Online marketplace for Photographers', 'Visual Blogging platform',
       'Food Customer analytics platform',
       'Professional Service Appointment booking service',
       'Scientific Horoscope Online Assistance platform',
       'Tech enabled AC bus service',
       'On-Demand App based Professional service provider',
       'Restaurant Reservation Platform', 'Cross-channel CRM platform',
       'Professional Custom creators Marketplace',
       'on-Demand Washing & Dry-Cleaning', 'On-Demand Beauty Service',