In [1]:
import numpy as np
import pandas as pd

In [2]:
funding_2025 = pd.read_csv("indian_startup_funding_2020_2025_sample.csv")
funding_2015 = pd.read_csv("startup_funding.csv")

In [3]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [4]:
funding_2015.tail()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [5]:
funding_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [6]:
funding_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   object
 1   Industry              1100 non-null   object
 2   SubVertical           1100 non-null   object
 3   City                  1100 non-null   object
 4   Investors             1100 non-null   object
 5   InvestmentType        1100 non-null   object
 6   InvestmentAmount_USD  1100 non-null   int64
 7   Date                  1100 non-null   object
dtypes: int64(1), object(7)
memory usage: 68.9+ KB

In [7]:
funding_2015 = funding_2015.drop(['Sr No', 'Remarks'], axis=1)

In [8]:
funding_2015.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [9]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [10]:
funding_2015.rename(
    columns={
        "Date dd/mm/yyyy":'Date',
        'Startup Name':'Startup',
        'Industry Vertical':'Industry',
        'SubVertical':'Sub Vertical',
        'City  Location':'City',
        'Investors Name':'Investors',
        'InvestmentnType':'Investment Type',
        'Amount in USD': 'Investment Amount($)'},
    inplace=True)

In [11]:
funding_2015.columns

Index(['Date', 'Startup', 'Industry', 'Sub Vertical', 'City', 'Investors',
       'Investment Type', 'Investment Amount($)'],
      dtype='object')

In [12]:
funding_2025.rename(
    columns = {
        'InvestmentType':'Investment Type',
        'SubVertical':'Sub Vertical',
        'InvestmentnType':'Investment Type',
        'InvestmentAmount_USD':'Investment Amount($)'
        }, 
    inplace=True)

In [13]:
funding_2025.columns

Index(['Startup', 'Industry', 'Sub Vertical', 'City', 'Investors',
       'Investment Type', 'Investment Amount($)', 'Date'],
      dtype='object')

In [14]:
funding_2025['Date'] = pd.to_datetime(funding_2025['Date'])

C:\Users\hp\AppData\Local\Temp\ipykernel_6060\2638179884.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  funding_2025['Date'] = pd.to_datetime(funding_2025['Date'])

In [15]:
funding_2025.sort_values('Date', ascending=False, inplace=True)

In [16]:
funding_2025.head()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,2025-06-24

In [17]:
funding_2025.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1100 entries, 213 to 363
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   object
 1   Industry              1100 non-null   object
 2   Sub Vertical          1100 non-null   object
 3   City                  1100 non-null   object
 4   Investors             1100 non-null   object
 5   Investment Type       1100 non-null   object
 6   Investment Amount($)  1100 non-null   int64
 7   Date                  1100 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 77.3+ KB

In [18]:
test = pd.to_datetime(
    funding_2015['Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

funding_2015.loc[test.isna(), 'Date']

192               05/072018
2571              01/07/015
2606    \\xc2\\xa010/7/2015
3029            22/01//2015
Name: Date, dtype: object

In [19]:
funding_2015['Date'] = funding_2015['Date'].str.replace('05/072018','05/07/2018')
funding_2015['Date'] = funding_2015['Date'].str.replace('01/07/015','01/07/2015')
funding_2015['Date'] = funding_2015['Date'].str.replace(r'\\xc2\\xa010/7/2015', '10/07/2015', regex=False)
funding_2015['Date'] = funding_2015['Date'].str.replace(r'22/01//2015', '22/01/2015')

In [20]:
funding_2015['Date'] = pd.to_datetime(funding_2015['Date'], format='mixed')

In [21]:
funding_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  3044 non-null   datetime64[ns]
 1   Startup               3044 non-null   object
 2   Industry              2873 non-null   object
 3   Sub Vertical          2108 non-null   object
 4   City                  2864 non-null   object
 5   Investors             3020 non-null   object
 6   Investment Type       3040 non-null   object
 7   Investment Amount($)  2084 non-null   object
dtypes: datetime64[ns](1), object(7)
memory usage: 190.4+ KB

In [199]:
funding = pd.concat([funding_2025, funding_2015])

In [200]:
funding.head()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,2025-06-24

In [201]:
funding.tail()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
3039,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",2015-01-29
3040,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",2015-01-29
3041,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",2015-01-30
3042,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,2015-01-30
3043,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",2015-01-31

In [202]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4140 non-null   object
 6   Investment Amount($)  3184 non-null   object
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 291.4+ KB

In [203]:
funding['Startup'].nunique()

2605

In [204]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna('unknown')
funding['Investment Amount($)']

213        168000
923      45929000
842         96000
236        141000
957         59000
          ...
3039    45,00,000
3040     8,25,000
3041    15,00,000
3042      unknown
3043     1,40,000
Name: Investment Amount($), Length: 4144, dtype: object

In [205]:
# Remove commas(,)
funding['Investment Amount($)'].astype('string') + ','
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('string').str.replace(',', '', regex=False)

In [206]:
funding['Investment Amount($)']

213       168000
923     45929000
842        96000
236       141000
957        59000
          ...
3039     4500000
3040      825000
3041     1500000
3042     unknown
3043      140000
Name: Investment Amount($), Length: 4144, dtype: string

In [207]:
funding['Investment Amount($)'][funding['Investment Amount($)'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Investment Amount($)
unknown               961
\\xc2\\xa0N/A           4
undisclosed             3
Undisclosed             3
\\xc2\\xa020000000      1
\\xc2\\xa016200000      1
\\xc2\\xa0600000        1
\\xc2\\xa0685000        1
\\xc2\\xa019350000      1
\\xc2\\xa05000000       1
\\xc2\\xa010000000      1
Name: count, dtype: Int64

In [208]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].str.replace(r'\\xc2\\xa0','')

In [209]:
funding['Investment Amount($)'] = pd.to_numeric(funding['Investment Amount($)'], errors='coerce')

funding['Investment Amount($)'].isna().sum()

np.int64(972)

In [210]:
check = funding.groupby('Startup').agg(
    Total_Rows=('Investment Amount($)', 'size'),
    NaN_Amount=('Investment Amount($)', 'count')
)

check['NaN_Amount'] = check['Total_Rows'] - check['NaN_Amount']

nan_values = check[check['Total_Rows'] == 1]

nan_values['NaN_Amount'].sum()

np.int64(705)

In [213]:
fill = funding.groupby('Startup')['Investment Amount($)'].transform('mean')
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna(fill)
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna(funding['Investment Amount($)'].mean())

In [214]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('string')
funding['Investment Amount($)'][funding['Investment Amount($)'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Series([], Name: count, dtype: Int64)

In [215]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('float')

In [216]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4140 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

In [217]:
funding['Investment Amount($)'].isna().sum()

np.int64(0)

In [239]:
funding['Investment Type'].isna().sum()

np.int64(4)

In [238]:
# funding['Investment Type'].value_counts()

In [237]:
funding['Investment Type'].unique()

array(['Pre-Series A', 'Series B', 'Seed', 'Bridge', 'Series A', 'Angel',
       'Series D', 'Series C', 'Debt', 'Growth', 'Pre-Seed',
       'Private Equity', 'Private Equity Round', 'Pre-series A',
       'Seed Round', 'Series F', 'Series E', 'Debt Funding', 'Series G',
       'Series H', 'Venture', 'Seed Funding', nan, 'Funding Round',
       'Corporate Round', 'Maiden Round', 'pre-series A',
       'Seed Funding Round', 'Single Venture', 'Venture Round',
       'Series J', 'Angel Round', 'pre-Series A', 'Venture - Series',
       'Bridge Round', 'Debt and Preference capital', 'Inhouse Funding',
       'Seed / Angel Funding', 'Pre Series A', 'Equity', 'Debt-Funding',
       'Mezzanine', 'Series B (Extension)', 'Equity Based Funding',
       'Private Funding', 'Seed funding', 'Private', 'Structured Debt',
       'Term Loan', 'PrivateEquity', 'Angel Funding', 'Crowd funding',
       'Crowd Funding'], dtype=object)

In [236]:
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Venture - Series Unknown','Venture - Series')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed/ Angel Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed / Angle Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed/Angel Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Angel / Seed Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed\\nFunding','Seed Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Private\\nEquity','Private Equity')

In [245]:
fill = funding.groupby('Startup')['Investment Type'].transform(
    lambda x: x.mode().iloc[0] if not x.mode().empty else 'Not Know'
)

funding['Investment Type'] = funding['Investment Type'].fillna(fill)

In [246]:
funding['Investment Type'].isna().sum()

np.int64(0)