In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
funding_2025 = pd.read_csv("indian_startup_funding_2020_2025_sample.csv")
funding_2015 = pd.read_csv("startup_funding.csv")

In [3]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [4]:
funding_2015.tail()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [5]:
funding_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [6]:
funding_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   object
 1   Industry              1100 non-null   object
 2   SubVertical           1100 non-null   object
 3   City                  1100 non-null   object
 4   Investors             1100 non-null   object
 5   InvestmentType        1100 non-null   object
 6   InvestmentAmount_USD  1100 non-null   int64
 7   Date                  1100 non-null   object
dtypes: int64(1), object(7)
memory usage: 68.9+ KB

In [7]:
funding_2015 = funding_2015.drop(['Sr No', 'Remarks'], axis=1)

In [8]:
funding_2015.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [9]:
funding_2025.head()

,Startup,Industry,SubVertical,City,Investors,InvestmentType,InvestmentAmount_USD,Date
0,Housejoy,EdTech,K12,Mumbai,Lightspeed India,Seed,199000,19-04-2023
1,Groww,Media,Streaming,Bengaluru,IFC,Seed,1668000,28-01-2025
2,Groww,Mobility,Ride Sharing,Hyderabad,"Nexus Venture Partners, Peak XV",Series B,38052000,14-03-2021
3,FarmBox,Consumer Electronics,Wearables,Gurugram,"Kalaari Capital, Y Combinator",Seed,455000,11-09-2023
4,Udaan,RealEstate,Rental Tech,Mumbai,Bessemer Venture Partners,Seed,89000,31-01-2024

In [10]:
funding_2015.rename(
    columns={
        "Date dd/mm/yyyy":'Date',
        'Startup Name':'Startup',
        'Industry Vertical':'Industry',
        'SubVertical':'Sub Vertical',
        'City  Location':'City',
        'Investors Name':'Investors',
        'InvestmentnType':'Investment Type',
        'Amount in USD': 'Investment Amount($)'},
    inplace=True)

In [11]:
funding_2015.columns

Index(['Date', 'Startup', 'Industry', 'Sub Vertical', 'City', 'Investors',
       'Investment Type', 'Investment Amount($)'],
      dtype='object')

In [12]:
funding_2025.rename(
    columns = {
        'InvestmentType':'Investment Type',
        'SubVertical':'Sub Vertical',
        'InvestmentnType':'Investment Type',
        'InvestmentAmount_USD':'Investment Amount($)'
        }, 
    inplace=True)

In [13]:
funding_2025.columns

Index(['Startup', 'Industry', 'Sub Vertical', 'City', 'Investors',
       'Investment Type', 'Investment Amount($)', 'Date'],
      dtype='object')

In [14]:
funding_2025['Date'] = pd.to_datetime(funding_2025['Date'])

C:\Users\hp\AppData\Local\Temp\ipykernel_8820\2638179884.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  funding_2025['Date'] = pd.to_datetime(funding_2025['Date'])

In [15]:
funding_2025.sort_values('Date', ascending=False, inplace=True)

In [16]:
funding_2025.head()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,2025-06-24

In [17]:
funding_2025.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1100 entries, 213 to 363
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               1100 non-null   object
 1   Industry              1100 non-null   object
 2   Sub Vertical          1100 non-null   object
 3   City                  1100 non-null   object
 4   Investors             1100 non-null   object
 5   Investment Type       1100 non-null   object
 6   Investment Amount($)  1100 non-null   int64
 7   Date                  1100 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 77.3+ KB

In [18]:
test = pd.to_datetime(
    funding_2015['Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

funding_2015.loc[test.isna(), 'Date']

192               05/072018
2571              01/07/015
2606    \\xc2\\xa010/7/2015
3029            22/01//2015
Name: Date, dtype: object

In [19]:
funding_2015['Date'] = funding_2015['Date'].str.replace('05/072018','05/07/2018')
funding_2015['Date'] = funding_2015['Date'].str.replace('01/07/015','01/07/2015')
funding_2015['Date'] = funding_2015['Date'].str.replace(r'\\xc2\\xa010/7/2015', '10/07/2015', regex=False)
funding_2015['Date'] = funding_2015['Date'].str.replace(r'22/01//2015', '22/01/2015')

In [20]:
funding_2015['Date'] = pd.to_datetime(funding_2015['Date'], format='mixed')

In [21]:
funding_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  3044 non-null   datetime64[ns]
 1   Startup               3044 non-null   object
 2   Industry              2873 non-null   object
 3   Sub Vertical          2108 non-null   object
 4   City                  2864 non-null   object
 5   Investors             3020 non-null   object
 6   Investment Type       3040 non-null   object
 7   Investment Amount($)  2084 non-null   object
dtypes: datetime64[ns](1), object(7)
memory usage: 190.4+ KB

In [22]:
funding = pd.concat([funding_2025, funding_2015])

In [23]:
funding.head()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,168000,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,45929000,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,96000,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,141000,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,59000,2025-06-24

In [24]:
funding.tail()

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
3039,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",2015-01-29
3040,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",2015-01-29
3041,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",2015-01-30
3042,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,2015-01-30
3043,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",2015-01-31

In [25]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4140 non-null   object
 6   Investment Amount($)  3184 non-null   object
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 291.4+ KB

In [26]:
funding['Startup'].nunique()

2605

## Clean Investment Amount($) column

In [27]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna('unknown')
funding['Investment Amount($)']

213        168000
923      45929000
842         96000
236        141000
957         59000
          ...
3039    45,00,000
3040     8,25,000
3041    15,00,000
3042      unknown
3043     1,40,000
Name: Investment Amount($), Length: 4144, dtype: object

In [28]:
# Remove commas(,)
funding['Investment Amount($)'].astype('string') + ','
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('string').str.replace(',', '', regex=False)

In [29]:
funding['Investment Amount($)']

213       168000
923     45929000
842        96000
236       141000
957        59000
          ...
3039     4500000
3040      825000
3041     1500000
3042     unknown
3043      140000
Name: Investment Amount($), Length: 4144, dtype: string

In [30]:
funding['Investment Amount($)'][funding['Investment Amount($)'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Investment Amount($)
unknown               961
\\xc2\\xa0N/A           4
undisclosed             3
Undisclosed             3
\\xc2\\xa020000000      1
\\xc2\\xa016200000      1
\\xc2\\xa0600000        1
\\xc2\\xa0685000        1
\\xc2\\xa019350000      1
\\xc2\\xa05000000       1
\\xc2\\xa010000000      1
Name: count, dtype: Int64

In [31]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].str.replace(r'\\xc2\\xa0','')

In [32]:
funding['Investment Amount($)'] = pd.to_numeric(funding['Investment Amount($)'], errors='coerce')

funding['Investment Amount($)'].isna().sum()

np.int64(972)

In [33]:
check = funding.groupby('Startup').agg(
    Total_Rows=('Investment Amount($)', 'size'),
    NaN_Amount=('Investment Amount($)', 'count')
)

check['NaN_Amount'] = check['Total_Rows'] - check['NaN_Amount']

nan_values = check[check['Total_Rows'] == 1]

nan_values['NaN_Amount'].sum()

np.int64(705)

In [34]:
fill = funding.groupby('Startup')['Investment Amount($)'].transform('mean')
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna(fill)
funding['Investment Amount($)'] = funding['Investment Amount($)'].fillna(funding['Investment Amount($)'].mean())

In [35]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('string')
funding['Investment Amount($)'][funding['Investment Amount($)'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Series([], Name: count, dtype: Int64)

In [36]:
funding['Investment Amount($)'] = funding['Investment Amount($)'].astype('float')

In [37]:
funding['Investment Amount($)'].isna().sum()

np.int64(0)

In [38]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4140 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Clean Investment Type column

In [39]:
funding['Investment Type'].isna().sum()

np.int64(4)

In [40]:
# funding['Investment Type'].value_counts()

In [41]:
funding['Investment Type'].unique()

array(['Pre-Series A', 'Series B', 'Seed', 'Bridge', 'Series A', 'Angel',
       'Series D', 'Series C', 'Debt', 'Growth', 'Pre-Seed',
       'Private Equity', 'Private Equity Round', 'Pre-series A',
       'Seed Round', 'Series F', 'Series E', 'Debt Funding', 'Series G',
       'Series H', 'Venture', 'Seed Funding', nan, 'Funding Round',
       'Corporate Round', 'Maiden Round', 'pre-series A',
       'Seed Funding Round', 'Single Venture', 'Venture Round',
       'Series J', 'Angel Round', 'pre-Series A',
       'Venture - Series Unknown', 'Bridge Round',
       'Debt and Preference capital', 'Inhouse Funding',
       'Seed/ Angel Funding', 'Pre Series A', 'Equity', 'Debt-Funding',
       'Mezzanine', 'Series B (Extension)', 'Equity Based Funding',
       'Private Funding', 'Seed / Angel Funding', 'Seed/Angel Funding',
       'Seed funding', 'Seed / Angle Funding', 'Angel / Seed Funding',
       'Private', 'Structured Debt', 'Term Loan', 'PrivateEquity',
       'Angel Funding', 'Seed\\\\nFunding', 'Private\\\\nEquity',
       'Crowd funding', 'Crowd Funding'], dtype=object)

In [42]:
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Venture - Series Unknown','Venture - Series')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed/ Angel Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed / Angle Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed/Angel Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Angel / Seed Funding','Seed / Angel Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Seed\\nFunding','Seed Funding')
funding['Investment Type'] = funding['Investment Type'].str.replace(r'Private\\nEquity','Private Equity')

In [43]:
fill = funding.groupby('Startup')['Investment Type'].transform(
    lambda x: x.mode().iloc[0] if not x.mode().empty else 'Not Know'
)

funding['Investment Type'] = funding['Investment Type'].fillna(fill)

In [44]:
funding['Investment Type'].isna().sum()

np.int64(0)

In [45]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4120 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Clean Investors column

In [46]:
funding['Investors'].value_counts()

Investors
Kalaari Capital                               42
Undisclosed Investors                         39
Y Combinator                                  31
Info Edge                                     31
Undisclosed investors                         30
                                              ..
Fairfax Holdings                               1
Tekne Capital Management LLC                   1
Sequoia India, NEA, Prime Venture Partners     1
Nexus Venture Partners, Mekin Maheshwari       1
UK based Group of Angel Investors              1
Name: count, Length: 2818, dtype: int64

In [47]:
funding['Investors'] = (
    funding['Investors']
    .str.replace(r'\\xc2\\xa0', ' ', regex=True)
    .str.replace(r'\\xe2\\x80\\x99s', "'", regex=True)
    .str.replace(r'\\xe2\\x80\\x93', '-', regex=True)
    .str.replace(r'\\xc3\\x98', 'O', regex=True)
    .str.replace(r'\\n', ' ', regex=True)
    .str.replace(r'\\x[0-9a-fA-F]{2}', "'", regex=True)

    # Remove extra whitespace
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [48]:
for i in funding['Investors'].unique():
    print(i)

Peak XV, Zodius Capital
Info Edge, Matrix Partners India, Tiger Global Management
Mirae Asset
Zodius Capital
IFC
Omidyar Network
Kalaari Capital
Bessemer Venture Partners
Info Edge, Mirae Asset, SoftBank Vision Fund
Ribbit Capital
Blume Ventures
IFC, Prosus Ventures, Ventures India
Bessemer Venture Partners, Prosus Ventures
Y Combinator
LCatterton, Lightspeed India
Matrix Partners India, Prosus Ventures
Blume Ventures, Elevation Capital
Info Edge, Sequoia Capital India
Accel, Kedaara Capital
Accel, Falcon Edge, Peak XV
Tiger Global Management
Falcon Edge
Matrix Partners India, Ventures India
Sequoia Capital India
A91 Partners, Sequoia Capital India
Mirae Asset, Tiger Global
Bessemer Venture Partners, Sequoia Capital India, Zodius Capital
Blume Ventures, Tiger Global Management
Nexus Venture Partners, Sequoia Capital India
Bessemer Venture Partners, Lightspeed India, Matrix Partners India
A91 Partners
Ventures India
Lightspeed India, Peak XV
Elevation Capital, Tiger Global Management
Info Edge
Omidyar Network, Tiger Global Management, Ventures India
Kedaara Capital, Sequoia Capital India, Y Combinator
Matrix Partners India
Blume Ventures, Kedaara Capital
Bessemer Venture Partners, Elevation Capital, Peak XV
Elevation Capital, Matrix Partners India
LCatterton
IFC, Mirae Asset
Nexus Venture Partners, Omidyar Network
Peak XV
Blume Ventures, Info Edge, Ribbit Capital
Nexus Venture Partners
Accel
Y Combinator, Zodius Capital
Peak XV, Ribbit Capital, Sequoia Capital India
Tiger Global
Lightspeed India, Omidyar Network
A91 Partners, Info Edge, Matrix Partners India
Bessemer Venture Partners, Kedaara Capital, Nexus Venture Partners
Lightspeed India, Sequoia Capital India
Blume Ventures, Info Edge
A91 Partners, SoftBank Vision Fund
Blume Ventures, SoftBank Vision Fund
Kedaara Capital, Lightspeed India
Prosus Ventures
Falcon Edge, Lightspeed India, Peak XV
Elevation Capital
Accel, Prosus Ventures
Matrix Partners India, Y Combinator
Falcon Edge, Info Edge, Tiger Global
IFC, Nexus Venture Partners
Matrix Partners India, Omidyar Network
IFC, Kedaara Capital
Info Edge, Y Combinator
Blume Ventures, Info Edge, Sequoia Capital India
Blume Ventures, LCatterton
Mirae Asset, Nexus Venture Partners
Info Edge, LCatterton, Ribbit Capital
Tiger Global, Tiger Global Management
IFC, Matrix Partners India, Nexus Venture Partners
Kedaara Capital
Info Edge, Ribbit Capital, Y Combinator
LCatterton, Sequoia Capital India, Tiger Global
Kedaara Capital, Mirae Asset
Sequoia Capital India, Tiger Global
Elevation Capital, Nexus Venture Partners
Bessemer Venture Partners, Lightspeed India
Accel, IFC, Omidyar Network
IFC, Sequoia Capital India
Accel, IFC, Nexus Venture Partners
Nexus Venture Partners, Y Combinator
Bessemer Venture Partners, Info Edge, Omidyar Network
Tiger Global, Zodius Capital
Nexus Venture Partners, Prosus Ventures
Mirae Asset, Ribbit Capital, Y Combinator
Elevation Capital, Kedaara Capital, Matrix Partners India
Blume Ventures, Kalaari Capital
Info Edge, Kedaara Capital
Accel, LCatterton, Tiger Global Management
SoftBank Vision Fund
LCatterton, Omidyar Network
Matrix Partners India, Ventures India, Y Combinator
Ribbit Capital, Zodius Capital
Mirae Asset, Sequoia Capital India
Mirae Asset, Tiger Global Management
Elevation Capital, Kedaara Capital, Omidyar Network
Info Edge, Mirae Asset, Prosus Ventures
Accel, Peak XV
Tiger Global Management, Zodius Capital
A91 Partners, Falcon Edge, Prosus Ventures
IFC, Peak XV
Bessemer Venture Partners, Tiger Global Management
Bessemer Venture Partners, Blume Ventures, Nexus Venture Partners
A91 Partners, Mirae Asset
Kedaara Capital, Zodius Capital
IFC, Ribbit Capital
Blume Ventures, Zodius Capital
Accel, Info Edge
Mirae Asset, Ribbit Capital
Info Edge, LCatterton, Zodius Capital
Kalaari Capital, Nexus Venture Partners, Ribbit Capital
Nexus Venture Partners, Tiger Global Management, Ventures India
Prosus Ventures, Ribbit Capital
A91 Partners, Sequoia Capital India, SoftBank Vision Fund
Bessemer Venture Partners, Lightspeed India, Omidyar Network
Bessemer Venture Partners, Nexus Venture Partners, Tiger Global
Blume Ventures, Kalaari Capital, Y Combinator
IFC, Omidyar Network
Elevation Capital, Kalaari Capital
Omidyar Network, Sequoia Capital India
Kalaari Capital, Nexus Venture Partners
IFC, Kalaari Capital, Sequoia Capital India
SoftBank Vision Fund, Tiger Global
Accel, Blume Ventures, Ventures India
Bessemer Venture Partners, Omidyar Network
Sequoia Capital India, Y Combinator
Lightspeed India
Bessemer Venture Partners, Peak XV
Accel, Blume Ventures, Kedaara Capital
Blume Ventures, Tiger Global, Y Combinator
Blume Ventures, Y Combinator
Lightspeed India, Tiger Global
Kedaara Capital, Sequoia Capital India
Accel, Sequoia Capital India
Bessemer Venture Partners, IFC
Kedaara Capital, SoftBank Vision Fund
IFC, Kalaari Capital
LCatterton, Zodius Capital
Peak XV, Prosus Ventures
A91 Partners, Bessemer Venture Partners, Matrix Partners India
Accel, Blume Ventures, Kalaari Capital
Accel, Peak XV, Ribbit Capital
Accel, Falcon Edge, Tiger Global Management
Matrix Partners India, Tiger Global
Lightspeed India, Nexus Venture Partners, Tiger Global
Peak XV, Ventures India
IFC, Tiger Global Management
Bessemer Venture Partners, LCatterton, Nexus Venture Partners
IFC, Matrix Partners India
Kalaari Capital, Y Combinator
Info Edge, Ventures India
Kalaari Capital, Ventures India
Lightspeed India, Peak XV, Zodius Capital
Accel, Falcon Edge
Nexus Venture Partners, Omidyar Network, Tiger Global Management
Lightspeed India, Matrix Partners India, Omidyar Network
SoftBank Vision Fund, Ventures India
Omidyar Network, SoftBank Vision Fund
Elevation Capital, Peak XV
Kalaari Capital, Mirae Asset
Prosus Ventures, Y Combinator
Elevation Capital, Ribbit Capital, Y Combinator
Accel, Zodius Capital
Falcon Edge, Tiger Global Management
Kedaara Capital, Tiger Global Management
Mirae Asset, Zodius Capital
A91 Partners, Ribbit Capital, Ventures India
Blume Ventures, Nexus Venture Partners, Tiger Global
Mirae Asset, SoftBank Vision Fund
A91 Partners, Falcon Edge, Zodius Capital
Kalaari Capital, Omidyar Network, Peak XV
Falcon Edge, Y Combinator
Info Edge, Peak XV
A91 Partners, Kedaara Capital, Tiger Global Management
Kedaara Capital, Ventures India
A91 Partners, Matrix Partners India, Mirae Asset
Info Edge, Tiger Global Management
Blume Ventures, Mirae Asset
Falcon Edge, Nexus Venture Partners
Peak XV, Ribbit Capital
Bessemer Venture Partners, Zodius Capital
Blume Ventures, Matrix Partners India
Elevation Capital, Sequoia Capital India
Accel, IFC
IFC, SoftBank Vision Fund
Ribbit Capital, Tiger Global
Nexus Venture Partners, Prosus Ventures, Ventures India
Elevation Capital, Info Edge, Matrix Partners India
IFC, Mirae Asset, Sequoia Capital India
Kalaari Capital, LCatterton, Zodius Capital
Elevation Capital, SoftBank Vision Fund, Ventures India
Elevation Capital, Zodius Capital
A91 Partners, Nexus Venture Partners, Y Combinator
Peak XV, Tiger Global Management
Kalaari Capital, Matrix Partners India
Info Edge, Mirae Asset
Bessemer Venture Partners, Ventures India
Mirae Asset, Omidyar Network
Matrix Partners India, Nexus Venture Partners, Zodius Capital
Ribbit Capital, SoftBank Vision Fund, Tiger Global Management
Bessemer Venture Partners, Omidyar Network, Sequoia Capital India
Falcon Edge, Prosus Ventures
IFC, Zodius Capital
LCatterton, Peak XV, Prosus Ventures
Prosus Ventures, Tiger Global Management
IFC, Peak XV, Sequoia Capital India
IFC, Mirae Asset, SoftBank Vision Fund
Kedaara Capital, Ribbit Capital
Omidyar Network, Ribbit Capital
Falcon Edge, Tiger Global
A91 Partners, Falcon Edge, Ribbit Capital
Bessemer Venture Partners, Kedaara Capital
Peak XV, Sequoia Capital India
Elevation Capital, Prosus Ventures, SoftBank Vision Fund
A91 Partners, Tiger Global
Kalaari Capital, Mirae Asset, Prosus Ventures
Info Edge, LCatterton, Lightspeed India
SoftBank Vision Fund, Y Combinator
Kalaari Capital, Kedaara Capital, Zodius Capital
Kedaara Capital, Y Combinator
Accel, Nexus Venture Partners
LCatterton, Peak XV
Falcon Edge, Omidyar Network
IFC, Matrix Partners India, Zodius Capital
Kedaara Capital, Ribbit Capital, Y Combinator
Ribbit Capital, Ventures India
Falcon Edge, Peak XV
Info Edge, Kalaari Capital, Matrix Partners India
Falcon Edge, Kedaara Capital
IFC, Tiger Global
Blume Ventures, Sequoia Capital India
Blume Ventures, Prosus Ventures
Prosus Ventures, SoftBank Vision Fund
LCatterton, Matrix Partners India, Ribbit Capital
Elevation Capital, SoftBank Vision Fund
Blume Ventures, IFC, Nexus Venture Partners
Accel, Tiger Global
Tiger Global Management, Y Combinator
Sequoia Capital India, Zodius Capital
Kalaari Capital, Lightspeed India
LCatterton, Mirae Asset
Matrix Partners India, Sequoia Capital India
Nexus Venture Partners, Peak XV
Elevation Capital, Ribbit Capital
Accel, Kalaari Capital, Ventures India
Accel, Mirae Asset, Ribbit Capital
Mirae Asset, Peak XV
Accel, Elevation Capital
Matrix Partners India, Zodius Capital
Elevation Capital, IFC, Zodius Capital
Kedaara Capital, LCatterton, Tiger Global Management
Blume Ventures, Elevation Capital, Nexus Venture Partners
A91 Partners, Falcon Edge, Omidyar Network
Omidyar Network, SoftBank Vision Fund, Y Combinator
A91 Partners, Kedaara Capital
Accel, Mirae Asset
Accel, Kalaari Capital, Ribbit Capital
Accel, Info Edge, Prosus Ventures
LCatterton, Ventures India
Lightspeed India, Ribbit Capital
Accel, Ribbit Capital
Falcon Edge, Info Edge, Tiger Global Management
Elevation Capital, Kedaara Capital, Nexus Venture Partners
LCatterton, Tiger Global Management, Y Combinator
Omidyar Network, Y Combinator
Accel, Tiger Global, Y Combinator
Falcon Edge, Sequoia Capital India, Ventures India
Info Edge, Lightspeed India
Matrix Partners India, Omidyar Network, Y Combinator
A91 Partners, Falcon Edge, SoftBank Vision Fund
Blume Ventures, IFC, Prosus Ventures
Prosus Ventures, Tiger Global, Y Combinator
A91 Partners, Lightspeed India
Blume Ventures, IFC
IFC, Lightspeed India, Mirae Asset
Lightspeed India, Matrix Partners India, Mirae Asset
Sequoia Capital India, Ventures India
Elevation Capital, Kedaara Capital, SoftBank Vision Fund
Blume Ventures, Peak XV, Ribbit Capital
Info Edge, SoftBank Vision Fund, Tiger Global
Kalaari Capital, Prosus Ventures, Sequoia Capital India
Nexus Venture Partners, SoftBank Vision Fund, Tiger Global Management
Falcon Edge, SoftBank Vision Fund, Y Combinator
Prosus Ventures, Ventures India
Accel, Sequoia Capital India, Ventures India
Mirae Asset, Ventures India
Info Edge, Omidyar Network
IFC, Ventures India
Blume Ventures, Ribbit Capital
Kedaara Capital, LCatterton
Tiger Global, Y Combinator
A91 Partners, Falcon Edge, Tiger Global
Ribbit Capital, SoftBank Vision Fund
A91 Partners, Peak XV
A91 Partners, Matrix Partners India
Mirae Asset, Omidyar Network, Tiger Global Management
Info Edge, Kalaari Capital, SoftBank Vision Fund
Kalaari Capital, Ribbit Capital
Elevation Capital, Ventures India
Accel, Prosus Ventures, SoftBank Vision Fund
Mirae Asset, Prosus Ventures
Blume Ventures, Ventures India
A91 Partners, Tiger Global Management, Y Combinator
Bessemer Venture Partners, Nexus Venture Partners
Info Edge, SoftBank Vision Fund
Accel, Tiger Global Management
Info Edge, Peak XV, SoftBank Vision Fund
Accel, Kalaari Capital, Peak XV
Accel, LCatterton, Mirae Asset
Elevation Capital, Falcon Edge
IFC, Ribbit Capital, Sequoia Capital India
Elevation Capital, Prosus Ventures
Nexus Venture Partners, Peak XV, Prosus Ventures
LCatterton, Mirae Asset, Nexus Venture Partners
Falcon Edge, Kalaari Capital, Omidyar Network
Omidyar Network, Ribbit Capital, Ventures India
Falcon Edge, Mirae Asset
Bessemer Venture Partners, LCatterton
Kedaara Capital, Prosus Ventures, Ribbit Capital
LCatterton, Tiger Global Management
Accel, Info Edge, Y Combinator
Mirae Asset, Nexus Venture Partners, Prosus Ventures
Elevation Capital, Kedaara Capital
Kalaari Capital, Zodius Capital
A91 Partners, Y Combinator
A91 Partners, Kalaari Capital, Ventures India
Prosus Ventures, Zodius Capital
Kalaari Capital, Nexus Venture Partners, Peak XV
A91 Partners, Bessemer Venture Partners
Bessemer Venture Partners, Y Combinator
Lightspeed India, Nexus Venture Partners
Kalaari Capital, Kedaara Capital
Elevation Capital, Matrix Partners India, Ribbit Capital
Info Edge, Ribbit Capital
Nexus Venture Partners, Ribbit Capital
A91 Partners, Kedaara Capital, LCatterton
Matrix Partners India, Peak XV
Peak XV, Tiger Global, Tiger Global Management
LCatterton, Ventures India, Y Combinator
Kedaara Capital, Tiger Global
IFC, Prosus Ventures
Tiger Global, Ventures India
Kedaara Capital, Lightspeed India, Ventures India
Kalaari Capital, Tiger Global, Y Combinator
Prosus Ventures, Tiger Global Management, Zodius Capital
Nexus Venture Partners, Zodius Capital
Accel, Bessemer Venture Partners, IFC
LCatterton, Prosus Ventures
IFC, Lightspeed India, Prosus Ventures
Kalaari Capital, LCatterton
Blume Ventures, Falcon Edge
Matrix Partners India, SoftBank Vision Fund
Bessemer Venture Partners, Tiger Global
Lightspeed India, Zodius Capital
LCatterton, SoftBank Vision Fund
Accel, Mirae Asset, SoftBank Vision Fund
Accel, Bessemer Venture Partners, Kalaari Capital
Accel, Falcon Edge, Omidyar Network
Omidyar Network, Peak XV, Sequoia Capital India
Info Edge, LCatterton, Nexus Venture Partners
Bessemer Venture Partners, Falcon Edge
Falcon Edge, IFC
Kalaari Capital, Tiger Global
Accel, Blume Ventures, IFC
Lightspeed India, Nexus Venture Partners, Y Combinator
Kedaara Capital, Peak XV
Elevation Capital, Kedaara Capital, Prosus Ventures
Lightspeed India, Mirae Asset, Prosus Ventures
Kedaara Capital, Nexus Venture Partners
Kalaari Capital, LCatterton, Ribbit Capital
Peak XV, Y Combinator
Bessemer Venture Partners, Kedaara Capital, Prosus Ventures
Info Edge, Prosus Ventures
A91 Partners, Bessemer Venture Partners, Blume Ventures
A91 Partners, Blume Ventures
Falcon Edge, Kedaara Capital, Tiger Global Management
A91 Partners, Kalaari Capital, SoftBank Vision Fund
LCatterton, Omidyar Network, Sequoia Capital India
A91 Partners, IFC
IFC, Y Combinator
Accel, Lightspeed India
Falcon Edge, Mirae Asset, Y Combinator
Omidyar Network, Sequoia Capital India, Y Combinator
Ventures India, Y Combinator
Falcon Edge, Sequoia Capital India, SoftBank Vision Fund
Falcon Edge, Sequoia Capital India
IFC, Info Edge, Kalaari Capital
Info Edge, Nexus Venture Partners, Tiger Global Management
Ribbit Capital, Sequoia Capital India
A91 Partners, Info Edge
Info Edge, Ribbit Capital, Tiger Global Management
Kedaara Capital, Mirae Asset, Sequoia Capital India
Kedaara Capital, Tiger Global Management, Ventures India
LCatterton, Prosus Ventures, Ribbit Capital
IFC, Kalaari Capital, Peak XV
Ribbit Capital, Tiger Global Management
Bessemer Venture Partners, Elevation Capital, Info Edge
Omidyar Network, Tiger Global
Kalaari Capital, Matrix Partners India, Tiger Global Management
Mirae Asset, SoftBank Vision Fund, Tiger Global
Falcon Edge, Ribbit Capital
Blume Ventures, Matrix Partners India, Ventures India
Peak XV, Tiger Global, Y Combinator
Elevation Capital, Omidyar Network, Prosus Ventures
Bessemer Venture Partners, Blume Ventures
Accel, Lightspeed India, Ribbit Capital
Ribbit Capital, Tiger Global Management, Zodius Capital
Elevation Capital, Kalaari Capital, Lightspeed India
Lightspeed India, Y Combinator
Mirae Asset, Y Combinator
Omidyar Network, Tiger Global Management, Y Combinator
Falcon Edge, Kalaari Capital
Kedaara Capital, Omidyar Network
Omidyar Network, Prosus Ventures
A91 Partners, IFC, Kedaara Capital
Falcon Edge, IFC, Ventures India
IFC, Lightspeed India, Ventures India
LCatterton, SoftBank Vision Fund, Tiger Global
Susquehanna Growth Equity
Vinod Khatumal
Sprout Venture Partners
Chiratae Ventures
Ant Financial
Sathguru Catalyzer Advisors
Ping An Global Voyager Fund
Mumbai Angels, Ravikanth Reddy
SAIF Partners, Spring Canter Investment Ltd.
Paytm, NPTK, Sabre Partners and Neoplux
Vertex Growth Fund
nan
Ruizheng Investment
Manipal Education and Medical Group (MEMG)
Sequoia, CapitalG, Accel
Sauce.vc, Rainforest Ventures
Prime Venture Partners, LetsVenture, PS1 Venture and GlobalLogic co-founder Rajul Garg
RB Investments
DG Daiwa Ventures, DG Incubation
Trifecta Capital Advisors
FinTech
Dream Incubator
Altimeter Capital, Sutter Hill Ventures
Startup Buddy
Amour Infrastructure
Ackermans & van Haaren, HealthQuad, Rebright Partners, Toppan Printing
Matrix Partners, Stellaris Venture Partners, Kalaari Capital
IAN Fund and DSG Consumer Partners
Vijay Shekhar Sharma
Lightbox
Altimeter Capital, DST Global
Ayushmann Khurana
Matrix Partners India, Sequoia India
SAIF Partners
TIW Private Equity
Exfinity Venture Partners
Breakthrough Energy Ventures
Endiya Partners
Bennett Coleman and Company Ltd (BCCL)
India Quotient, Axilor Ventures
SC GG India Mobility Holdings LLC
Sequoia India
Azim Premji, Binny Bansal
Pine Labs Pte Ltd
Naspers
MS Dhoni
March Capital Partners
XL Innovate
Rashmi Daga (founder, FreshMenu), Raveen Sastry (co-founder, Myntra) and Mitesh Shah (finance chief, BookMyShow)
RPS Ventures
One97 Communications Ltd.
Growth DNA
Vir Sanghvi
Softbank Vision Fund
Westbridge Capital
Lok Capital, IIFL Wealth
WaterBridge Ventures
Kapil Dev
DIG Investment Ab, Deshe Holdings, Samih Toukan and Hussam Khoury
Artha Venture
Qatar Investment Authority
Composite Capital Management, Sequoia Capital India, Tiger Global Management
Undisclosed
Ventureast
Binny Bansal
Multiple Angel Investors
General Atlantic
Anicut Capital
Goldman Sachs, Accel Partners and Qualcomm
Matrix Partners
Insight Partners
Triton Investment Advisors, Pidilite Industries director Ajay Parekh
Blume Ventures and RTP Global
Shell Foundation, DILA CAPITAL, Engie RDE Fund, EcoEnterprise Fund, EDFIMC (ElectriFI), Endeavor Catalyst Fund, CoCapital, Triodos, Alpha Mundi, and Lendahand
IAN Fund
Qiming Venture Partners
WestBridge Capital
Alteria Capital
Mumbai Angels
Tata Sons
C4D Partners
Indian Angel Network and other angel investors, Innov8 founder Ritesh Malik, Josh Talks founders Supriya Paul and Shobha Banga, and former Hero Corporate president Rohit Chanana
Goldman Sachs Investment Partners and Silicon Valley-based Accel, Wellington, Sequoia Capital, B Capital, LightStreet, Sands Capital and International Finance Corporation,
Sachin Bansal
Equanimity Ventures
Korea Investment Partners, Vertex Ventures
Sixth Sense Ventures
Eight Roads
Prasid Uno Family Trust
Unilever, Beehive Capital Advisor, ABCOM Investments, Parekh Marine Transport,
Orchid India, Hornbill Orchid India Fund, Chiratae Ventures (formerly IDG Ventures), 3one4 Capital, Lasmer NV
Unnamed angel investors
Lightspeed India Partners
Milestone
Supera Pte Ltd
Kalyan Krishnamurthy
Sequoia India, Tiger Global Management, Accel Partners
BAC Acquisitions, Unifi AIF, BRD Securities, Northern R Capital
New Atlantic Ventures
021 Capita, Binny Bansal
India Quotient and LetsVenture\'\'\'s Angel Fund
Sequoia Capital and Temasek Holdings, EDBI, Burda Principal Investments, and Sofina
LetsVenture, PitchRight Venture, 91SpringBoard, AL Nour International Holdings and Mark V Investments
DiDi Chuxing
Sequoia India, Hillhouse Capital, Alphabet\'\'\'s growth investment arm Capital G and Axis Bank
Iron Pillar, Perceptive Advisors, Romulus Capital and Kalaari Capital
MASSIF, a Dutch government fund
Stellaris Venture Partners
Steadview Capital and Vy Capital.
Individual Investors
Omphalos Ventures India LLP
Info Edge, AET Fund, Akatsuki and Incubate Fund from Japan and Better Capital AngelList syndicate.
Venture Highway, GREE Ventures, Space Matrix, Individual Investors
Lead Angels Network
Norwest Venture Partners, CDC Group, the UK\'\'\'s Development Finance Institution and P Surendra Pai
Shunwei Capital, DST Partners and RPS Ventures
RB Investments, Singapore
Mayfield Fund
Stevens Creek Ventures
Venture Catalysts
Sistema Asia Fund, VC Samsung NEXT, Chiratae Ventures, Inventus Capital, Blume Ventures and Innoven Capital.
Individual investors
Teachers Insurance and Annuity Association (TIAA)

In [49]:
funding.loc[funding['Investors'].isna()]

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
13,InCred,Finance,Non-Banking Financial Company,Mumbai,NaN,Debt Funding,5.900000e+06,2019-12-16
46,MyPetrolPump,Retail,Fuel Delivery,Bengaluru,NaN,Seed Funding Round,1.600000e+06,2019-01-08
154,3HCare,Healthcare,Healthcare Service Provider,Delhi,NaN,Seed / Angel Funding,1.000000e+06,2018-04-09
168,My OmNamo,Consumer Internet,Holy Platform Offering Customised Puja Package...,Mumbai,NaN,Seed / Angel Funding,1.000000e+06,2018-07-08
178,Enakshi,Consumer Internet,AI Based Solutions Platform,Ahemadabad,NaN,Seed / Angel Funding,1.148110e+05,2018-08-16
180,Finzy,Finance,Online Loan Matchmaking Platform,Bengaluru,NaN,Seed / Angel Funding,1.000000e+06,2018-08-20
188,True North,Finance,Private Equity Firm,Mumbai,NaN,Private Equity,6.000000e+08,2018-08-30
208,HousingMan,Consumer Internet,Property Discovery Platform,Bengaluru,NaN,Seed / Angel Funding,1.500000e+06,2018-07-20
210,Yulu Bikes,Technology,Bicycle-Sharing Platform,Bengaluru,NaN,Seed / Angel Funding,2.077046e+07,2018-07-23
260,PaisaDukan,Consumer Internet,P2P Lending Platform,Mumbai,NaN,Seed / Angel Funding,2.250000e+05,2018-07-05
283,Finzy,Consumer Internet,Online Loan Matchmaking Platform,Bengaluru,NaN,Seed / Angel Funding,1.300000e+06,2018-02-04
290,Kriger Campus,Ed-Tech,Mobile-Based Education Network,Delhi,NaN,Seed / Angel Funding,4.614000e+04,2018-09-04
306,Mihuru,Finance,Online Platform Providing Micro Loans For Air ...,Mumbai,NaN,Seed / Angel Funding,1.500000e+05,2018-04-23
345,Roadcast,Technology,Fleet management and asset monitoring platform,Delhi,NaN,Private Equity,2.500000e+05,2018-03-28
396,Kinsane Entertainment Inc,Entertainment,Digital Entertainment for Children,Mumbai,NaN,Seed / Angel Funding,2.500000e+06,2018-09-01
458,Cash Suvidha,E-Commerce,Online Micro-Lending Platform,Delhi,NaN,Debt Funding,2.700000e+06,2017-12-15
684,MyCity4kids,Consumer Internet,parenting blog and kids\\xe2\\x80\\x99 events ...,Gurgaon,NaN,Seed Funding,2.077046e+07,2017-06-07
843,Cube Consumer Services,Consumer Internet,Finance management Mobile app,Mumbai,NaN,Seed Funding,2.077046e+07,2017-05-29
2113,Zapluk,"Health, Wellness & Beauty Services App",NaN,Hyderabad,NaN,Seed Funding,2.077046e+07,2015-01-12
2204,LoanBaba,Online Loans Marketplace,NaN,Mumbai,NaN,Seed Funding,3.200000e+05,2015-03-11
2278,JustRide,Self Driven Rental Car Platform,NaN,Mumbai,NaN,Private Equity,2.000000e+06,2015-11-27
2408,Zapyle,pre-used apparel shopping mobile app,NaN,Bangalore,NaN,Seed Funding,1.000000e+06,2015-11-09
2690,kWatt Solutions,Renewable energy solutions,NaN,Mumbai,NaN,Seed Funding,5.000000e+05,2015-05-06
2812,KeepTrax,Location Based App,NaN,Dallas / Hyderabad,NaN,Seed Funding,1.000000e+06,2015-04-04

In [50]:
funding['Investors'] = funding['Investors'].fillna('Unknown')

In [51]:
funding['Investors'].isna().sum()

np.int64(0)

In [52]:
funding['Investors'].nunique()

2819

In [53]:
# Find Invalid name
funding['Investors'][funding['Investors'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Investors
Kalaari Capital                               42
Undisclosed Investors                         39
Info Edge                                     31
Y Combinator                                  31
Blume Ventures                                30
                                              ..
Fairfax Holdings                               1
Tekne Capital Management LLC                   1
Sequoia India, NEA, Prime Venture Partners     1
Nexus Venture Partners, Mekin Maheshwari       1
UK based Group of Angel Investors              1
Name: count, Length: 2819, dtype: int64

In [54]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  3964 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Clean City column

In [55]:
funding['City'].isnull().sum()

np.int64(180)

In [56]:
funding['City'].value_counts()

City
Bangalore             700
Mumbai                671
New Delhi             421
Gurgaon               287
Bengaluru             248
                     ...
Delhi & Cambridge       1
Bhubneswar              1
Srinagar                1
Rourkela                1
Dallas / Hyderabad      1
Name: count, Length: 112, dtype: int64

In [57]:
funding['City'].unique()

array(['Noida', 'Pune', 'Mumbai', 'Delhi', 'Ahmedabad', 'Gurugram',
       'Kolkata', 'Bengaluru', 'Hyderabad', 'Chennai', 'Gurgaon',
       'New Delhi', 'Faridabad', 'San Francisco', 'San Jose,', 'Amritsar',
       'Kormangala', 'Tulangan', 'Burnsville', 'Menlo Park', 'Palo Alto',
       'Santa Monica', 'Singapore', 'Taramani', 'Andheri', 'Chembur',
       'Nairobi', 'Haryana', 'New York', 'Karnataka', 'Mumbai/Bengaluru',
       'Bhopal', 'Bengaluru and Gurugram', 'India/Singapore', 'Jaipur',
       'India/US', 'Nagpur', 'Indore', 'New York, Bengaluru',
       'California', 'India', 'Ahemadabad', 'Rourkela', 'Srinagar',
       'Bhubneswar', 'Chandigarh', 'Delhi & Cambridge', 'Kolkatta',
       'Coimbatore', 'Bangalore', 'Udaipur', nan, 'Ahemdabad',
       'Bhubaneswar', 'Surat', 'Goa', 'Uttar Pradesh', 'Nw Delhi', 'Gaya',
       'Vadodara', 'Trivandrum', 'Missourie', 'Panaji', 'Gwalior',
       'Karur', 'Udupi', 'Kochi', 'Agra', 'Bangalore/ Bangkok', 'Hubli',
       'Kerala', 'Kozhikode', 'US', 'Siliguri', 'USA', 'Lucknow',
       'Kanpur', 'SFO / Bangalore', 'London', 'Seattle / Bangalore',
       'Pune/Seattle', 'Pune / Dubai', 'Bangalore / SFO', 'Varanasi',
       'New Delhi / US', 'Mumbai / UK', 'Jodhpur', 'Hyderabad/USA',
       'Boston', 'Bangalore / Palo Alto', 'Mumbai / NY', 'USA/India',
       'Goa/Hyderabad', 'Noida / Singapore', 'Belgaum', 'Pune / US',
       'Chennai/ Singapore', 'Pune / Singapore', 'Bangalore / San Mateo',
       'New York/ India', 'US/India', 'Gurgaon / SFO', 'Bangalore / USA',
       'New Delhi/ Houston', 'Mumbai / Global', 'India / US',
       '\\\\xc2\\\\xa0Noida', '\\\\xc2\\\\xa0Bangalore',
       '\\\\xc2\\\\xa0Gurgaon', '\\\\xc2\\\\xa0New Delhi',
       '\\\\xc2\\\\xa0Mumbai', 'New Delhi / California',
       'Dallas / Hyderabad'], dtype=object)

In [58]:
funding['City'] = (
    funding['City']
    .str.replace(r'\\\\xc2\\\\xa0', '', regex=True)
    .str.strip()
)

funding['City'] = funding['City'].replace({
    'Gurgaon': 'Gurugram',
    'New Delhi': 'Delhi',
    'Nw Delhi': 'Delhi',
    'Bangalore': 'Bengaluru',
    'Kormangala': 'Bengaluru',
    'Ahemadabad': 'Ahmedabad',
    'Ahemdabad': 'Ahmedabad',
    'Bhubneswar': 'Bhubaneswar',
    'Kolkatta': 'Kolkata',
    'Taramani': 'Chennai',
    'Andheri': 'Mumbai',
    'Chembur': 'Mumbai',
    'Haryana': 'Gurugram',
    'Karnataka': 'Bengaluru',
    'Uttar Pradesh': 'Noida',
    'Kerala': 'Kochi',
    'Panaji': 'Goa',
    'San Jose,': 'San Jose',
    'US': 'United States',
    'USA': 'United States',
})

funding['City'].value_counts()

City
Bengaluru              952
Mumbai                 674
Delhi                  587
Gurugram               451
Pune                   218
                      ...
Tulangan                 1
SFO / Bangalore          1
London                   1
Seattle / Bangalore      1
Dallas / Hyderabad       1
Name: count, Length: 89, dtype: int64

In [59]:
funding['City'].unique()

array(['Noida', 'Pune', 'Mumbai', 'Delhi', 'Ahmedabad', 'Gurugram',
       'Kolkata', 'Bengaluru', 'Hyderabad', 'Chennai', 'Faridabad',
       'San Francisco', 'San Jose', 'Amritsar', 'Tulangan', 'Burnsville',
       'Menlo Park', 'Palo Alto', 'Santa Monica', 'Singapore', 'Nairobi',
       'New York', 'Mumbai/Bengaluru', 'Bhopal', 'Bengaluru and Gurugram',
       'India/Singapore', 'Jaipur', 'India/US', 'Nagpur', 'Indore',
       'New York, Bengaluru', 'California', 'India', 'Rourkela',
       'Srinagar', 'Bhubaneswar', 'Chandigarh', 'Delhi & Cambridge',
       'Coimbatore', 'Udaipur', nan, 'Surat', 'Goa', 'Gaya', 'Vadodara',
       'Trivandrum', 'Missourie', 'Gwalior', 'Karur', 'Udupi', 'Kochi',
       'Agra', 'Bangalore/ Bangkok', 'Hubli', 'Kozhikode',
       'United States', 'Siliguri', 'Lucknow', 'Kanpur',
       'SFO / Bangalore', 'London', 'Seattle / Bangalore', 'Pune/Seattle',
       'Pune / Dubai', 'Bangalore / SFO', 'Varanasi', 'New Delhi / US',
       'Mumbai / UK', 'Jodhpur', 'Hyderabad/USA', 'Boston',
       'Bangalore / Palo Alto', 'Mumbai / NY', 'USA/India',
       'Goa/Hyderabad', 'Noida / Singapore', 'Belgaum', 'Pune / US',
       'Chennai/ Singapore', 'Pune / Singapore', 'Bangalore / San Mateo',
       'New York/ India', 'US/India', 'Gurgaon / SFO', 'Bangalore / USA',
       'New Delhi/ Houston', 'Mumbai / Global', 'India / US',
       'New Delhi / California', 'Dallas / Hyderabad'], dtype=object)

In [60]:
funding['City'] = funding['City'].fillna('Unknown')

In [61]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          3208 non-null   object
 3   City                  4144 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Clean Sub Vertical column

In [62]:
funding['Sub Vertical'].value_counts()

Sub Vertical
Fashion                                       67
Grocery                                       67
Supply Chain                                  52
Marketplace                                   45
Food Delivery                                 35
                                              ..
Beauty products discovery platform             1
Tech driven Insurance platform                 1
CSR and sustainability management platform     1
Location tracking solutions                    1
Interior Design Marketplace                    1
Name: count, Length: 1983, dtype: int64

In [63]:
for i in funding['Sub Vertical'].unique():
    print(repr(i))

'Marketplace'
'UpSkilling'
'Pharmacy'
'Health Analytics'
'Grocery'
'HRTech'
'Fleet Management'
'Micro Mobility'
'Last Mile'
'PropTech'
'EV'
'Food Delivery'
'Diagnostics'
'Security'
'Fashion'
'InsurTech'
'Smart Home'
'Smart Farming'
'Supply Chain'
'DevTools'
'Analytics'
'B2B SaaS'
'Content'
'Coding Bootcamp'
'Quick Commerce'
'Cloud Kitchen'
'K12'
'Social'
'Test Prep'
'MarTech'
'WealthTech'
'Automation'
'D2C'
'Wearables'
'Streaming'
'Audio'
'NeoBank'
'Rental Tech'
'E-Retail'
'Home Services'
'Payments'
'Ride Sharing'
'Lending'
'Telemedicine'
'E-learning'
'App based shuttle service'
'Retailer of baby and toddler products'
'Online Investment'
'Embroiled Clothes For Women'
'Open-market, freight management platform'
'Online Food Delivery Platform'
'Agritech'
'Automobile'
'Satellite Communication'
'Logistics Services and Solutions'
'Food Solutions For Corporate'
'Online Meat And Seafood Ordering Startup'
'Non-Banking Financial Company'
'Experience Discovery Platform'
'Real money based gaming startup'
'Online Eyewear Shopping Portal'
'Business and customer engagement tools'
"Men's Health and Wellness brand"
'Elearning'
'Indian Burger Brand'
'Healthcare services'
'Financial Services To MSMEs'
'Social gaming platform'
'Recovery software'
'Electric bike rental'
'Virtual e-commerce platform'
'B2B platform for medical supplies'
'Scooter sharing app'
'Music Education'
'Mobile Wallet'
'Delivery Service'
'Business development'
'Beauty and Grooming'
'Financial Services'
'Invoice discounting platform and SME lending marketplace'
'Digital marketing firm'
'Education Technology'
'Building automation system'
'Deep-technology'
'Consumer Electronics, Home Appliances'
'Wearable Fitness Bands'
'Mobile-based Accounting Software'
'Automotive'
'Supply Chain Management'
'Fuel Delivery'
'VC Funds'
'Last-mile retail transaction technology'
'Social Commerce'
'Car Retail'
'Conversational AI'
'Road Safety Analytics'
'Low carb food for Diabetics'
'Digital Lending Platform'
'Wealth Management'
'B2B Foodtech'
'University Admissions'
'Product Review'
'Grocery Delivery'
'Bike Taxi'
'Auto Insurance'
'Big Data'
'Consulting'
'Cabs'
'Speech Recognition'
'Digital Vending Machine'
'Education'
'Industrial Tools and Equipments'
'Logistics'
'Smartphone Operating System'
'Primary care medical network'
'Clothes and Apparel'
'Full-stack career platform'
'Real Estate'
'Brewery'
'Hospitality'
'FinTech'
'Optimization'
'Artificial Intelligence'
'Hybrid Reactor Biodigestor'
'Renewable Energy'
'E-Books'
'Video Platform'
'Online Lending Platform'
'Dockless Scooter Rental Company'
'Digital Documentation'
'Fashion and Shopping'
'Beauty and Wellness Industry'
'Electric Vehicle'
'Fresh Agriculture Produces'
'Retail'
'Online Medicine'
'Waste Management'
'Travel'
'Organic wellness'
'Banking'
'Fashion and Apparel'
'Mobile analytics and marketing'
'Software Solutions'
'Lending Platform'
'Bus Aggregation'
'Supply-chain technology solutions'
'Fashion & Apparel'
'Anti-Pollution'
'Budget Rooms'
'Online Marketplace'
'Specialty pharmaceutical'
'Non-banking financial company'
'Hyperlocal Content'
'Home services marketplace'
'Platform for travel agents'
'Video-based certification, trainings'
'eCommerce'
'Real Estate, ERP'
'Regional Flavours'
'MSME Finance'
'Mobile e-Sports'
'Meat Retail Chain'
'POS For Online Ordering'
'Micro-delivery grocery service'
'On-Demand Drivers'
'Car Wash'
'Robotics'
'Wellness Coach'
'Personalized Learning'
'SME Funding'
'Art'
'Digital Onboarding Solution'
'AI Platform'
'SME Lending'
'Video Sharing'
'Mens Wear'
'Wine'
'New and Used Cars Platform'
'Co-Working'
'Largest Trucking Platform'
'Book Trucks Online'
'Online Pharmacy Chain'
'Logistics and Shipping'
'News and ebooks Mobile App\\\\xc2\\\\xa0'
'Healthcare Service Provider'
'Online Travel Agecy'
'Online Marketplace For Multi-brand Beauty Cosmetic and Wellness Products'
'Computer Vision And Artificial Intelligence (Ai) Platform'
'Online Gaming Platform'
'Online Marketplace For Mother and Babycare Products'
'AI-Based Energy Optimisation and Control Provider'
'Online Marketplace For Pharmaceutical Products'
'Online Micro Lending Marketplace'
'Online lending Platform'
'Personalisation Technology Firm Focusing On The Food And Beverage Industry'
'Patient Financing Platform'
'Social Media and Chat Entertainment Platform'
'Online Home Rental Marketplace'
'Holy Platform Offering Customised Puja Packages To Individuals and Corporates'
'Assisted E-commerce Platform'
'Online Travel Aggregator'
'Real-time Mobile App Management'
'Online Bike Rental Marketplace'
'UPI Payments App'
'e-learning Platform'
'Consumer Financing Platform'
'Rural E-commerce Platform'
'AI Based Solutions Platform'
'Online Restaurant Table Reservation Platform'
'Online Loan Matchmaking Platform'
'Online Organic Juice Delivery Service'
'Applied Artificial Intelligence and IoT focused\\\\xc2\\\\xa0Platform'
'Online Indian Car Rental Platform'
'\\\\xc2\\\\xa0Customer Sourcing Platform\\\\xc2\\\\xa0'
'Local Language Health Content App'
'Post-Purchase Customer Engagement Platform\\\\xc2\\\\xa0'
'Private Equity Firm'
'HR Virtual Agent For Employees'
'Online Food Delivery'
'E-commerce Fulfilment Platform'
'Online Lending Platform For Salaried Professionals'
'Online Insurance Selling Platform'
'Online Platform For Risk-Assessment Services For Real Estate Investments'
'Online Platform That Sells Direct Plans Of Mutual Funds'
'Online Platform That Connects Brands With Freelance Sales Professionals'
'Med-tech Platform Providing Care For Newborns'
'Lending Platform For Micro and Small Enterprises'
'Mobile Storefront And Commerce Platform For Sellers'
'Online Micro Lending Platform'
'Artificial intelligence-based sales acceleration software platform'
'Home diagnostics services provider'
'A Doctor-Patient Engagement Platform'
'Online Lending Platform For SME'
'Online Used Car Marketplace'
'Subscription-Only News Website'
'Online Ticketing Platform'
'Property Discovery Platform'
'Online Consumer Lending Platform'
'Bicycle-Sharing Platform'
'Media Analytics'
'Nanotechnology Company Specializing In Graphene'
'Skill Learning Platform'
'Online Insurance Startup'
'Mobile-First Video Blogging App'
'Data Analytics Firm'
'Software-As-A-Service Platform'
'Travel-Focused Tech Startup'
'Unified Global Investments Ecosystem'
'Bus Aggregation Platform'
'Health and fitness Platform'
'Non-Bank Lending Platform For SME'
'Health and Well being Platform'
'Credit-Based Lending Marketplace For Small And Medium Enterprises'
'Sales Analytics and Enablement Platform'
'Online Marketplace For Handicrafts, Handlooms And Local Produce'
'Online Crowdfunding Platform'
'Online Healthcare Aggregator'
'Online Marketplace For Resellers'
'Specialised diagnostics Platform'
'Supplychain Finance'
'Fashion e-tailer'
'Hyperlocal Delivery Platform'
'An Online Platform That Connects Ayurveda Doctors With Patients'
'Mass Market Mutual Fund Investment Platform'
'A Local Discovery App For Dining-Out, Party, Leisure and Events'
'Online Home Furnishing Solutions'
'Cybersecurity Specialist'
'Prosthetics Manufacturers'
'Data Analytics (SaaS)'
'Education Services Provider'
'Online Rental Marketplace'
'Trade Finance Firm'
'Online Motorbike And Scooter Rental Platforms'
'Digital Payment Platform For Beverage Delivery'
'App-based investment platform'
'Digital Payment Platform'
'Data Driven Intelligence Solutions Platform'
'E-commerce Logistics Platform'
'An AI Platform Offering Automated Customer Service Software'
'Online Education Platform'
'An Artificial Intelligence-Based Recruitment Platform'
'Aggregator For Packaging Material'
'SaaS'
'P2P Lending Platform'
'AI product company For Health and Life Insurane Companies'
'Agri-tech'
'Beauty e-tailer'
'Doctor-Consultation App'
'Online Video Creation Platform'
'Micro-Delivery Grocery Startup'
'Micro Lending Platform'
'Products For Shoolgoing Children'
'Housing Finance For Low-Income Families'
'Designer Of Toys and Learning Projects For Kids'
'Oxygen Optimiser Manufacturer'
'Online Insurance Platform'
'Home Healthcare Aggregator'
'Mobile Payments Technology Platform'
'Events and Activities Discovery Platform'
'Iot Application Platform In Agriculture'
'Lending Platform For SMEs'
'Online Fitness Discovey Platform'
'Social Media Anlaytics Platform'
'Enhanced Employee Engagement Platform'
'Loans and Services To Affordable Private Schools in India'
'Interactive Online Tutoring Platform'
'Digital Financial Services Platform'
'Fashion Accessories Etailer'
'Blockchain Platform'
'Mobile-Based Education Network'
'Digital Lending Platform In Logistics'
'Online Travel Marketplace'
'Platform To Discover Healthcare Financing Options'
'Online Platform For Luxury Hotel Stay For Business Travelers'
'Connected Care App For Pregnant Women'
'Online Insurance Aggregator'
'Online Eyewear Retailer'
'Online Baby care Products'
'AI Based Expense Management Platform'
'Mobile Balance Checking App'
'AI Driven Health tech Platform'
'Digitized Health-Tech Solutions For Practitioners'
'Online Platform Providing Micro Loans For Air Travel'
'Women Focussed Digital Media Platform'
'Online Travel Ticketing Platform'
'Online Pharmacy Store'
'Online Lending MarketPlace'
'Online Stock Broker'
'B2C Online Loans Marketplace'
'Online Scholarship Portal'
'Online Furniture Store'
'Online Financial Planning'
'Therapeutics'
'Genetic Screening, DNA Diagnostics Labs & Research Centers'
'Online Lending'
'Cloud based Online Hotel Management Software'
'Health Service Aggregator Platform'
'Creative Design, Brand, Media and Technology Platform Solutions'
'Online Furniture Shopping Store'
'Hyperlocal Discovery'
'Healthcare Aggregator'
'Online Communication and Collaboration Platform For Educational Institutions'
'Online Grocery Shop'
'Ready To cook Food Solution'
'Technology enabled equitable healthcare for India'
'Online Raw Meat E-tailer'
'Customer Success Software for B2B SaaS'
'Consumer Technology and Artificial Intelligence Based Aggregator App'
'Micro Jobs Provider For Students'
'Subscription Billing & Recurring Payments Software'
'Online loan platform'
'Voice-based assistant platform'
'Online ordering solution for restaurants and food chains'
'Fleet management and asset monitoring platform'
'Micro lending company'
'News portal'
'Professional Car Drivers Hiring App'
'O2O fashion ecommerce platform'
'Online Grocery & Food Store'
'Food Ordering and Restaurant Discovery'
'E-Publishing'
'Super-specialty Hospital'
'Online platform for Higher Education Services'
'Online Food Marketplace'
'Preventive Health Checkup'
'Online Portal for Diet,fitness and Beauty'
'Enterprise Contract Management Platform'
'Mobile Weight Loss Coach'
'Virtual health clinics'
'Online Gold Loan'
'Marketing Cloud for consumer businesses'
'B2B Marketplace'
'Online Selling'
'Mobile Solutions for Social Impact'
'Individualised Progressive Learning Program'
'Integrated Kids Engagement Company'
'mobile payment platform'
'Online Pet Care Products'
'Online Retailing'
'Expense Management'
'Fin-Tech'
'Cloud-based Software'
'Robotic InspectionStartup'
'Digital Design'
'AI platform for hospitality industry'
'Online Music Streaming'
'Cancer radiology'
'Mobile App Analytics'
'Food and Beverages'
'Sports Nutrition Supplement etailer'
'Digital Entertainment for Children'
'Personal Assistant'
'Agricultural Loan'
'Medical Devices'
'Algorithmic Trading'
'Payment Gateway'
'Venture Capital'
'IT'
'Artificial Intellegence'
'Alternative Lending'
'Online Grocery'
'Digital Lending'
'Coaching Services'
'Eyewear'
'Hemostatic Dressing Solutions'
'Technology'
'Online Services'
'Hygiene'
'Browser Testing'
'Virtual Reality'
'Mobile Payment Platform'
'Fitness'
'Education Solutions'
'IoT based air pollution controller'
'Daily Task Management Mobile App'
'Residential Project'
'Mobile Learning Management Platform'
'Bicycle sharing Platform'
'Off-grid solar products platform'
'Child Learning & Development Platform'
'Mobile point of sale services provider'
'Home Decor and Online Fashion Portal'
'Super speciality Hospitals'
'"Women\\\\\'s Fashion Clothing Online Platform"'
'Mobile News Curation App'
'Online Platform Selling Indian Tea Globally'
'Educational Platform to Learn Mathematics'
'Assisting Visually Impaired to learn through Braille'
'Furniture Rental Platform'
'Hotel Aggregator Platform'
'Platform based on 3D printing and Digital Manufacturing'
'Adaptive Fraud Intelligence Platform'
'Fashion and Lifestyle Coupon Platform'
'Gamification Platform to train Sales People'
'Mobile Games Development Firm'
'Mobile Application for Doctor Consultation'
'Artificial Intelligence Platform to Raise Funds'
'Fresh Indian Tea Selling Platform across 112 countries'
'Hyperlocal Video Information Sharing Platform'
'Mobile App for Network of Doctors'
'Online Furniture Marketplace'
'Provides Business Insights using Drone Imaginary'
'Beauty Products Online Marketplace'
'Online Micro-Lending Platform'
'Weather Forecast Platform'
'Online Courses and Mentoring from Experts'
'SaaS based Big Data Analytics Platform'
'Online Poker Platform'
'Vernacular and Video Content Platform'
'Micro finance institution providing small ticket unsecured loans to women'
'Regional Operating System for Smartphones'
'Ecommerce enabler platform'
'Online Gifting Platform'
'Online Spects Platform for Men and Women'
'Online vehicle service booking platform'
'Realty Tech Startup solving real life Interior Designing problems'
'Business & SME Loans provider'
'Aadhaar-based API provider'
'Online Grocery Store'
'Online Tutorial Marketplace'
'Online Fantasy Games'
'VR based Spiritual platform'
'Real time data analytics & reporting'
'Financial Technology Research Platform'
'Customer Engagement Platform'
'Doctor Patient Communication platform'
'Wearable tech and Internet of Things platform'
'Distance Education Learning Platform'
'Mutual Fund Investment App'
'Online platform for Agricultural products'
'IoT based Tech Startup'
'Enrolment Management Platform'
'Saas based Corporate Travel Management Solution'
'Augmented Reality based Tech platform'
'Big Data based analytics platform'
'Online Gifting platform'
'Celebrity fashion accessories and merchandise'
'Healthy & Nutrition based snacks online platform'
'AI based FinTech platform'
'Banking Software License Platform'
'Social Healthcare Enterprise'
'WiFi Analytics Platform'
'Storytelling platform'
'End-to-End property management for landlords living away'
'Placement preparation and career growth training platform'
'Self riding bike rental program'
'Bike and Taxi pooling online platform'
'Big Data Analytics Platform'
'Managed Cloud Environment Solutions'
'AI based pharmacy drugs insights platform'
'Healthcare facilities at doorstep'
'Vehicle loan approval platform'
'Tech based investor firm'
'Online Hotel Reservation Platform'
'Viral Content and storytelling platform'
'Venture Capitalist'
'IoT and SaaS based transportation platform'
'Diversified Financial'
'Identity management platform'
'Virtual Reality based gaming platform'
'Designer-led consumer products'
'Online Truck aggregator platform'
'Health and fitness based mobile App'
'Student accommodation platform'
'Home Loans Aggregation platform'
'Home Loan Down payment assistance program'
'App based cab hailing services'
'P2P platform for Fashion sales'
'Education collaboration platform'
'Digital Wallet'
'Local Recommendations and Discoveries Platform'
'rooftop solar platform'
'Ecommerce Portal for Used Goods'
'Mobile repair and Refurbishment platform'
'Fresh Produce SCM company'
'Self Drive car and bike rental platform'
'Student Micro-financing platform'
'Agriculture Supply Chain management solutions'
'Home Interior Designing Seller'
'Treasury Risk Management Solution'
'Auto Service Logistics & SAAS platform'
'Education Technology platform'
'AI-powered anti-fraud solutions'
'AI-powered deep learning solutions'
'online restaurant reservation platform'
'Online Reseller Network'
'Medical Transportation Services'
'Education Network for Institutions, teachers & Students'
'Online insurance policy aggregator'
'home maintenance services platform'
'Online Chai ordering platform'
'Micro-lending platform'
'Food Ordering Portal'
'Online Financial Marketplace'
'App building platform'
'B2B Logistics provider'
'Online peer-to-peer lending platform'
'Mobile based learning app'
'Cold pressed Juice maker'
'app-only lending platform'
'Machine learning based parking discovery'
'Cold Chain monitoring solution'
'Herbal energy shot maker'
'SME lending platform'
'Online Learning Platform'
'Frozen Meat provider'
'Real Estate content portal'
'Contract Automation'
'Online Grocery portal'
'B2B Finance & Fulfilment Network'
'Credit + payment mobile app'
'Payments Platform for Marketplaces and Fintechs'
'Agriculture Technology'
'Online Pharmacy'
'Equity Stock Exchange'
'Online B2B store for office supplies'
'Online Doctor Discovery platform'
'Online Photography platform'
'Application Performance Acceleration'
'online lending platform'
'EduTech Platform'
'Online travel booking platform'
'Medical Diagnostic Solutions'
'Buying Club for Small Businesses'
'Online Credit scoring platform'
'Pet care portal & mobile app'
'Branded budget hotels marketplace'
'Online Unsecured Lending platform'
'online babycare products marketplace'
'Ecommerce portal for senior citizens'
'Agre-Tech Mobile app'
'Logistics Solutions provider'
'Healthcare Services Aggregator'
'Health Food etailer'
'Healthcare services portal'
'Imaging Technology for Armed Forces'
'Smart Parking Enabler'
'Content marketing platform'
'women focussed customer-to-customer reseller network'
'udget hotel marketplace'
'Online learning platform'
'Telecom & IoT platform'
'co-working space provider'
'Virtual Reality gaming and entertainment platform'
'Bike Rental Platform'
'Online Tutoring Platform'
'Pregnancy & Baby Care product etailer'
'mobile-first communication platform for on-field staff,'
'Integrated receivables software solutions'
'Technology-Empowered Healthcare Solutions'
'financial services firm'
'E-sports platform'
'Co-working spaces'
'Home Furnishing & Building material marketplace'
'Online Travel Agency'
'Omni-channel web commerce solutions provider'
'Scooter Rental Platform'
'SME Marketing Management Solution'
'Food Delivery platform'
'Crop Technology Solutions'
'Bike Aggregator Mobile App'
'Sports & Sport related equipment portal'
'Online consumer lending platform'
'Matchmaking app for the differently abled'
'Language learning Mobile App'
'Geospatial Technology-based SaaS solutions'
'O2O fashion discovery platform'
'Car repair and Servicing Platform'
'Luxury Helicopter Tourism Services portal'
'Local Language Health Information portal'
'Defense Tech & Aerospace startup'
'Predictive Care Platform'
'Digital Marketing Agency'
'DIY Ecommerce platform'
'healthcare service aggregator'
'On-Demand Logistics Service provider'
'Recruitment Portal'
'Tea Delivery Portal & offline stores'
'Health Products & Services Aggregator'
'Restaurant Management Solutions'
'Fashion Resale Marketplace'
'Warehouse Aggregator'
'Skincare Speciality services'
'Hospital Management Software'
'foreign exchange services'
'Mobile based Logistics Service'
'Agriculture Supply Chain solutions'
'Online milk delivery'
'Co-Living space aggregator'
'Mobile games developer'
'App based cab aggregation Service'
'Sports Content Mobile App'
'Personal Loans & EMI solutions platform'
'Unsecured Small Business Loans'
'Payment Solution Mobile app'
'Building material online store'
'speech recognition startup'
'E-Tech platform'
'instant messaging platform'
'Govt service application portal'
'Online Grocery platform'
'Cloud data protection and management solutions'
'Men Grooming product etailer'
'Operations and manpower outsourcing'
'Software & Mobile app development platform'
'mPOS solutions provider'
'Online printing marketplace'
'Online Doctor Discovery Platform'
'Restaurant & Hotel CRM platform'
'End to End health and wellness platform.'
'Healthtech IoT platform'
'SAAS based sales force automation services'
'Budget Hotel Aggregator platform'

In [64]:
funding['Sub Vertical'] = (
    funding['Sub Vertical']
    .str.replace(r'\\xc2\\xa0', ' ', regex=True)
    .str.replace(r'\\xc3\\xa9', ' ', regex=True)
    .str.replace(r'\\xe2\\x80\\x99', " ", regex=True)
    .str.replace(r'\\xc3\\xa9', ' ', regex=True)
    .str.replace(r'\\n', ' ', regex=True)
    .str.replace(r'\\', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
)

In [65]:
# Find Invalid name
funding['Sub Vertical'][funding['Sub Vertical'].str.contains(r'[A-Za-z]', regex=True, na=False)].value_counts()

Sub Vertical
Fashion                                       67
Grocery                                       67
Supply Chain                                  52
Marketplace                                   45
Food Delivery                                 35
                                              ..
Beauty products discovery platform             1
Tech driven Insurance platform                 1
CSR and sustainability management platform     1
Location tracking solutions                    1
Interior Design Marketplace                    1
Name: count, Length: 1983, dtype: int64

In [66]:
funding['Sub Vertical'] = funding['Sub Vertical'].fillna('Unknown')

In [67]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              3973 non-null   object
 2   Sub Vertical          4144 non-null   object
 3   City                  4144 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Handle Industry column

In [68]:
funding['Industry'].value_counts()

Industry
Consumer Internet                       941
Technology                              478
eCommerce                               186
E-commerce                              102
Retail                                   90
                                       ...
Music Streaming mobile app                1
Raw Meat & Ready to eat food etailer      1
Gym Discovery platform                    1
Online Purchase rewards app               1
Online Travel Marketplace                 1
Name: count, Length: 828, dtype: int64

In [69]:
funding['Industry'].nunique()

828

In [70]:
funding['Industry'].isna().sum()

np.int64(171)

In [71]:
funding['Industry'] = (
    funding['Industry']
    .str.replace(r'\\\\xc2\\\\xa0', ' ', regex=True)
    .str.replace(r'\\\\xe2\\\\x80\\\\x93', '-', regex=True)
    .str.replace(r'\\\\xe2\\\\x80\\\\x99', "'", regex=True)
    .str.replace(r'\\\\xc3\\\\xa9', 'e', regex=True)
    .str.replace(r'\\n', ' ', regex=True)
    .str.replace(r'\\', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
)

In [72]:
fixes = {
    'Fiinance': 'Finance',
    'eCommece': 'E-commerce',
    'Saas': 'SaaS',
    'Edtech': 'EdTech',
    'Ed-Tech': 'EdTech',
    'Ed-tech': 'EdTech',
    'Ed-Tech Platform': 'EdTech',
    'Fintech': 'FinTech',
    'Fin-Tech': 'FinTech',
    'Financial Tech': 'FinTech',
    'Agtech': 'AgriTech',
    'Ecommerce': 'E-commerce',
    'ECommerce': 'E-commerce',
    'eCommerce': 'E-commerce',
    'ecommerce': 'E-commerce',
    'E-Commerce': 'E-commerce',
    'Food Tech': 'FoodTech',
    'Food-Tech': 'FoodTech',
    'Health-Tech': 'HealthTech',
    'Health Care': 'Healthcare',
    'healthcare': 'Healthcare',
    'RealEstate': 'Real Estate',
    'Reality': 'Real Estate',
    'Automobile': 'Automotive',
    'Auto': 'Automotive',
    'Video Games': 'Gaming',
    'AI': 'Artificial Intelligence',
    'IT': 'Information Technology',
    'Tech': 'Technology',
}

text_fixes = {
    'Clud based Learning platform': 'Cloud Based Learning Platform',
    'Home Design & D cor platform': 'Home Design & Decor Platform',
    'Home Design & D cor solutions': 'Home Design & Decor Solutions',
    'Online home d cor marketplace': 'Online Home Decor Marketplace',
    'Online Home D cor': 'Online Home Decor',
    'Chain of Tea Caf s': 'Chain of Tea Cafes',
    'usiness expense management': 'Business Expense Management',
    'Consumer Interne': 'Consumer Internet',
    'User Engagment & Analytics platform': 'User Engagement & Analytics Platform',
    'Rental Accomodation finder': 'Rental Accommodation Finder',
}

funding['Industry'] = funding['Industry'].replace(text_fixes)

funding['Industry'] = funding['Industry'].replace(fixes)

In [73]:
funding['Industry'].nunique()

799

In [74]:
funding['Industry'].value_counts()

Industry
Consumer Internet                  942
Technology                         480
E-commerce                         390
EdTech                              99
FinTech                             91
                                  ...
global community for travellers      1
Prepaid Bill manager App             1
Mobile Only Shopping Assistant       1
Mobile Messaging Assistant App       1
Online Travel Marketplace            1
Name: count, Length: 799, dtype: int64

In [75]:
print("Unique values:", funding['Industry'].nunique())
print("Missing values:", funding['Industry'].isna().sum())

Unique values: 799
Missing values: 171

In [76]:
funding['Industry'] = funding['Industry'].fillna('Unknown')

funding['Industry'].isna().sum()

np.int64(0)

In [77]:
funding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4144 entries, 213 to 3043
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Startup               4144 non-null   object
 1   Industry              4144 non-null   object
 2   Sub Vertical          4144 non-null   object
 3   City                  4144 non-null   object
 4   Investors             4144 non-null   object
 5   Investment Type       4144 non-null   object
 6   Investment Amount($)  4144 non-null   float64
 7   Date                  4144 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 291.4+ KB

## Clean Startup column

In [78]:
print("Raw unique startup count:", funding['Startup'].nunique())
print("Missing values in Startup:", funding['Startup'].isna().sum())

Raw unique startup count: 2605
Missing values in Startup: 0

In [79]:
import re

# Dictionary for known brand capitalizations & variation mappings
special_brands = {
    "1mg": "1mg",
    "20dresses": "20Dresses",
    "360ride": "360Ride",
    "3dexter": "3Dexter",
    "3hcare": "3HCare",
    "3rdflix": "3rdFlix",
    "48east": "48East",
    "4tigo": "4tigo",
    "5th vital": "5th Vital",
    "6degree": "6Degree",
    "75f": "75F",
    "91springboard": "91SpringBoard",
    "99games": "99Games",
    "99perhour": "99PerHour",
    "9stacks": "9Stacks",
    "byju's": "Byju's",
    "byjus": "Byju's",
    "byju": "Byju's",
    "ola": "Ola",
    "ola cabs": "Ola",
    "olacabs": "Ola",
    "oyo": "OYO Rooms",
    "oyo rooms": "OYO Rooms",
    "oyorooms": "OYO Rooms",
    "paytm": "Paytm",
    "paytm marketplace": "Paytm",
    "flipkart": "Flipkart",
    "swiggy": "Swiggy",
    "lendingkart": "Lendingkart",
    "lending kart": "Lendingkart",
    "urbanclap": "UrbanClap",
    "urban clap": "UrbanClap",
    "newsinshorts": "NewsInShorts",
    "news in shorts": "NewsInShorts",
    "phonepe": "PhonePe",
    "phone pe": "PhonePe",
    "pinelabs": "Pine Labs",
    "pine labs": "Pine Labs",
    "razorpay": "Razorpay",
    "razor pay": "Razorpay",
    "traveltriangle": "TravelTriangle",
    "travel triangle": "TravelTriangle",
    "urbanladder": "Urban Ladder",
    "urban ladder": "Urban Ladder",
    "wowexpress": "WoW Express",
    "wow express": "WoW Express",
    "zestmoney": "ZestMoney",
    "zest money": "ZestMoney",
    "i2i funding": "i2i Funding",
    "impactguru": "ImpactGuru",
    "impact guru": "ImpactGuru",
    "indialends": "IndiaLends",
    "india lends": "IndiaLends",
    "lendenclub": "LenDenClub",
    "lenden club": "LenDenClub",
    "letstransport": "LetsTransport",
    "lets transport": "LetsTransport",
    "loantap": "LoanTap",
    "loan tap": "LoanTap",
    "log9 materials": "Log9 Materials",
    "log 9 materials": "Log9 Materials",
    "milkbasket": "Milkbasket",
    "milk basket": "Milkbasket",
    "mswipe": "mSwipe",
    "ekincare": "eKincare",
    "mpaani": "mPaani",
    "zovi": "Zovi",
    "holachef": "HolaChef",
    "homelane": "HomeLane",
    "icanstay": "I Can Stay",
    "icustommadeit": "ICustomMadeIt",
    "inclov": "Inclov",
    "industrybuying": "IndustryBuying",
    "inkmonk": "InkMonk",
    "inmobi": "InMobi",
    "jolly food fellow": "Jolly Food Fellow",
    "jollyfoodfellow": "Jolly Food Fellow",
    "justride": "JustRide",
    "kaaryah": "KAARYAH",
    "kredx": "KredX",
    "leap india": "Leap India",
    "legalraasta": "LegalRaasta",
    "letsmd": "LetsMD",
    "livspace": "LivSpace",
    "loanzen": "LoanZen",
    "logicroots": "LogicRoots",
    "mamaearth": "Mamaearth",
    "mfine": "MFine",
    "mind your fleet": "Mind Your Fleet",
    "mindyourfleet": "MindYourFleet",
    "mobiefit": "MobieFit",
    "mobikwik": "MobiKwik",
    "mycity4kids": "MyCity4Kids",
    "nearbuy": "NearBuy",
    "nestaway": "NestAway",
    "netmeds": "NetMeds",
    "nightstay": "NightStay",
    "notesgen": "Notesgen",
    "ofbusiness": "OfBusiness",
    "paysense": "PaySense",
    "peppertap": "PepperTap",
    "pharmeasy": "PharmEasy",
    "pipabella": "Pipa Bella",
    "pipa bella": "Pipa Bella",
    "pitstop": "PitStop",
    "pi ventures": "Pi Ventures",
    "play your sport": "Play Your Sport",
    "policybazaar": "PolicyBazaar",
    "policy bazaar": "PolicyBazaar",
    "practo": "Practo",
    "pratilipi": "Pratilipi",
    "qwikspec": "QwikSpec",
    "raw pressery": "RAW Pressery",
    "rawpressery": "RAW Pressery",
    "reddoorz": "RedDoorz",
    "renewbuy": "RenewBuy",
    "renew buy": "RenewBuy",
    "rentomojo": "RentoMojo",
    "rollmafia": "RollMafia",
    "roll mafia": "Roll Mafia",
    "room on call": "Room On Call",
    "salebhai": "SaleBhai",
    "satvacart": "SatvaCart",
    "shadowfax": "ShadowFax",
    "shoekonnect": "ShoeKonnect",
    "shopclues": "ShopClues",
    "shopkirana": "ShopKirana",
    "shubh loans": "Shubh Loans",
    "shubhloans": "ShubhLoans",
    "sigtuple": "SigTuple",
    "smartcoin": "SmartCoin",
    "snapbizz": "SnapBizz",
    "spareshub": "SparesHub",
    "spares hub": "Spares Hub",
    "squadrun": "SquadRun",
    "stalk buy love": "StalkBuyLove",
    "stalkbuylove": "StalkBuyLove",
    "stayzilla": "Stayzilla",
    "stitchwood": "StitchWood",
    "styledotme": "StyleDotMe",
    "tails life": "TailsLife",
    "tailslife": "TailsLife",
    "tapchief": "TapChief",
    "teabox": "TeaBox",
    "tea box": "TeaBox",
    "testbook": "TestBook",
    "timesaverz": "TimeSaverz",
    "tinmen": "TinMen",
    "tonetag": "ToneTag",
    "tone tag": "ToneTag",
    "touchkin": "TouchKin",
    "townscript": "TownScript",
    "tripshelf": "TripShelf",
    "trip shelf": "TripShelf",
    "ue life sciences": "UE LifeSciences",
    "vanity cube": "VanityCube",
    "vanitycube": "VanityCube",
    "voxweb": "VoxWeb",
    "yourdost": "YourDOST",
    "zendrive": "ZenDrive",
    "zipgrid": "ZipGrid",
    "zoomcar": "ZoomCar"
}

def clean_startup(name):
    if pd.isna(name):
        return 'Unknown'
    s = str(name).strip()
    
    # 1. Handle byte escape representations of quotes, hyphens, non-breaking spaces
    s = re.sub(r'\\xe2\\x80\\x99|\\xe2\\x80\\x98', "'", s)
    s = re.sub(r'\\xe2\\x80\\x93|\\xe2\\x80\\x94', "-", s)
    s = re.sub(r'\\xc2\\xa0', " ", s)
    
    # 2. Remove byte escape sequences and whitespace escapes
    s = re.sub(r'\\x[a-fA-F0-9]{2}', '', s)
    s = re.sub(r'\\[nrt]', ' ', s)
    
    # 3. Clean quotes, backslashes, and replacement characters
    s = s.replace("\\\'", "'")
    s = s.replace('\\', '')
    s = s.replace('"', '')
    s = s.replace('#', '')
    s = s.replace("`", "'")
    s = s.replace("’", "'")
    s = s.replace("\ufffd", "'")
    
    # 4. Remove URL schemes, www, trailing paths, domain extensions
    s = re.sub(r'^https?://', '', s, flags=re.IGNORECASE)
    s = re.sub(r'^www\.', '', s, flags=re.IGNORECASE)
    s = re.sub(r'\/(.*)$', '', s)
    s = re.sub(r'\.(com|in|co|net|org)$', '', s, flags=re.IGNORECASE)
    
    # 5. Remove parenthetical details
    s = re.sub(r'\s*\([^)]*\)', '', s)
    
    # 6. Strip corporate suffixes
    s = re.sub(r'\s+(Pvt\.?\s*Ltd\.?|Private\s+Limited|Inc\.?|LLP\.?|Ltd\.?|Corp\.?)$', '', s, flags=re.IGNORECASE)
    s = re.sub(r'\s+Technologies\s+(Pvt\.?\s*Ltd\.?|Private\s+Limited)$', '', s, flags=re.IGNORECASE)
    
    # 7. Normalize spaces
    s = re.sub(r'\s+', ' ', s).strip()
    
    # 8. Check special brand dictionary
    s_lower = s.lower()
    if s_lower in special_brands:
        return special_brands[s_lower]
        
    # 9. Apply Proper Word/Title Casing if lower/upper
    if s.islower() or s.isupper():
        words = s.split(' ')
        cap_words = []
        for w in words:
            if not w:
                continue
            parts = w.split('-')
            cap_parts = []
            for p in parts:
                if "'" in p:
                    sub = p.split("'")
                    cap_p = sub[0].capitalize() + "'" + (sub[1].lower() if len(sub) > 1 else '')
                else:
                    cap_p = p.capitalize()
                cap_parts.append(cap_p)
            cap_words.append('-'.join(cap_parts))
        s = ' '.join(cap_words)
        
    return s

funding['Startup'] = funding['Startup'].apply(clean_startup)
funding['Startup'] = funding['Startup'].fillna('Unknown')

In [80]:
# Verify Startup column unique values & casing
print("Cleaned & Title-Cased unique startup count:", funding['Startup'].nunique())
print("Missing values after cleaning:", funding['Startup'].isna().sum())

Cleaned & Title-Cased unique startup count: 2456
Missing values after cleaning: 0

In [81]:
funding['Startup'].value_counts().head(25)

Startup
Ola              27
OYO Rooms        23
Udaan            17
Paytm            16
NoBroker         16
Meesho           16
Delhivery        16
DriveEdge        15
Swiggy           15
FreshTech        14
Zomato           14
Housejoy         14
Razorpay         14
LogiMart         14
Flipkart         13
Cars24           13
Porter           13
Nykaa            13
Unacademy        13
Byju's           13
HomeAnalytics    12
FarmBox          12
SkillFlow        12
CoreConnect      12
ShareChat        12
Name: count, dtype: int64

In [82]:
funding

,Startup,Industry,Sub Vertical,City,Investors,Investment Type,Investment Amount($),Date
213,SkillSolutions,AgriTech,Marketplace,Noida,"Peak XV, Zodius Capital",Pre-Series A,1.680000e+05,2025-06-30
923,QuantumSolutions,EdTech,UpSkilling,Pune,"Info Edge, Matrix Partners India, Tiger Global...",Series B,4.592900e+07,2025-06-29
842,Paytm,HealthTech,Pharmacy,Mumbai,Mirae Asset,Seed,9.600000e+04,2025-06-27
236,Housejoy,HealthTech,Health Analytics,Noida,Zodius Capital,Seed,1.410000e+05,2025-06-27
957,Nykaa,Retail,Grocery,Delhi,IFC,Bridge,5.900000e+04,2025-06-24
...,...,...,...,...,...,...,...,...
3039,Printvenue,Unknown,Unknown,Unknown,Asia Pacific Internet Group,Private Equity,4.500000e+06,2015-01-29
3040,Graphene,Unknown,Unknown,Unknown,KARSEMVEN Fund,Private Equity,8.250000e+05,2015-01-29
3041,Mad Street Den,Unknown,Unknown,Unknown,"Exfinity Fund, GrowX Ventures.",Private Equity,1.500000e+06,2015-01-30
3042,Simplotel,Unknown,Unknown,Unknown,MakeMyTrip,Private Equity,2.077046e+07,2015-01-30
3043,Couponmachine,Unknown,Unknown,Unknown,UK based Group of Angel Investors,Seed Funding,1.400000e+05,2015-01-31

In [83]:
for i in funding.columns:
    if funding[i].dtype == 'object':
        funding[i] = funding[i].str.strip()

In [87]:
for value in sorted(funding['Startup'].dropna().unique(), key=str.lower):
    print(repr(value))

'121Policy'
'19th Mile'
'1Crowd'
'1mg'
'20Dresses'
'33Coupons'
'360Ride'
'3Dexter'
'3HCare'
'3rdFlix'
'48East'
'4tigo'
'5th Vital'
'6Degree'
'75F'
'91SpringBoard'
'99Games'
'99PerHour'
'9Stacks'
'A&R Bon Vivants'
'AadharAPI'
'Aadyah'
'Aagaar'
'Aahaa'
'Aahaa Stores'
'Aarav UAV'
'Aasaanjobs'
'Aashiyaan'
'Aavishkaar-Intellecap Group'
'AbeRuk'
'Abhibus'
'ABI Health'
'Absentia'
'Absentia VR'
'Ace Turtle'
'Ace2three'
'Acko'
'Actionable Analytics'
'Active AI'
'Active.ai'
'Actofit'
'ActOnMagic'
'Ad2pro'
'Address Health'
'AdmitKard'
'AdPushUp'
'AdStringO'
'AdUrCup'
'Advanced Structures India'
'Advantage Club'
'Advenio'
'AdWyze'
'Adytude'
'AEON Learning'
'Aequm'
'AerMed'
'AeroAnalytics'
'AeroAnalytics_861'
'AeroHub'
'AeroStack'
'Affimity'
'Affordplan'
'Agara Labs'
'AgentDesks'
'Agricxlab'
'AgriFit'
'AgriHive'
'AgriSense'
'Agrostar'
'Agrowave'
'AHA Taxis'
'AirCTO'
'AirMed Labs'
'Airpay'
'Airwood'
'AirZaar'
'Aisle'
'Akosha'
'Alef Mobitech'
'AllIzHealth'
'Allygrow Technologies'
'AlmaConnect'
'AlmaMapper'
'Alpha Capital'
'Alteria Capital'
'Alternacare'
'Altizone'
'Amagi Media Labs'
'Ambee'
'American Vision'
'Ameyo'
'Amigobulls'
'Ampere'
'Ampere Vehicles'
'Anakage'
'Anandakanda'
'Anchanto'
'Annapurna Finance'
'Antuit'
'Appario Retail'
'Appbase'
'AppBrowzer'
'AppDaily'
'Appedo'
'Appie'
'AppilyEver'
'Appknox'
'Applicate'
'Applied Solar Technologies'
'AppLop'
'Applop'
'AppsDaily'
'Appsdaily'
'Appvigil'
'AppVirality'
'Arcatron'
'Arcatron Mobility'
'Ark Robot'
'Arkin Net'
'Arohan Financial Services'
'Arth DesignBuild'
'Artoo'
'Arya.ai'
'Aryaka'
'Asia Institute Of Medical Science'
'AskMyGift'
'Asocon'
'Ather Energy'
'Athletto'
'Atlan'
'Atomberg'
'Atomberg Technology'
'Attune Technologies'
'Augrav'
'Autobix'
'AutoFlow'
'AutoFlow_933'
'AutoGrid'
'AutoMart'
'Automation Anywhere'
'Autorox'
'AutoSense'
'AutoStack'
'AutoStack_777'
'Avagmah'
'Avail Finance'
'AvailFinance'
'Avanti Learning'
'Avenue Growth'
'Avishkaar Box'
'Awaaz De'
'Awesummly'
'Awfis'
'Awign'
'Axio'
'Axtria'
'Aye Finance'
'AYE Finance'
'AyeFinance'
'Azah'
'Azuro'
'B9 Beverages'
'Babajobs'
'Baby Berry'
'BabyChakra'
'Babychakra'
'Babygogo'
'BabyonBoard'
'Badiyajobs'
'BaggOut'
'Balance App'
'Banihal'
'Bank Bazaar'
'BankBazaar'
'BankerBay'
'Bats on delivery'
'Baxi'
'Be U Salons'
'BeaconsTalk'
'Beardo'
'BeatRoute'
'BedBathMore'
'Belita'
'Belong'
'Benepik'
'Bestdealfinance'
'BetaOut'
'Betaout'
'Better Mortgage'
'BetterButter'
'Betterplace'
'BetterPlace'
'Bevy'
'Bewakoof'
'Beyond Evolution'
'Bharat Bazaar'
'BharatPe'
'Bhive'
'BHIVE Workspace'
'BhiveWorkspace'
'BiBox'
'Bidgely'
'Big Basket'
'Big Fish Ventures'
'BigBasket'
'BigStylist'
'Bikxie'
'BillDesk'
'Billion Loans'
'Bira91'
'Biryani Blues'
'Biryani By Kilo'
'Bite Club'
'Biteclub'
'BitGiving'
'Bitla Software'
'Biz2Credit'
'Bizom'
'Bizongo'
'Black Soil'
'Black White Orange'
'Black White Orange Brands'
'BlackBuck'
'Blackbuck'
'Blinge'
'BlogBeats'
'Blood n Care'
'Blowhorn'
'Blubox'
'Blue Box Media'
'Blue Tokai Coffee'
'Bluebirch'
'Bluegape'
'BlueRise'
'BlueSpace'
'BlueStone'
'Bluestone'
'BlueTech'
'Board Infinity'
'Bobble'
'BoiBanit'
'Bollant Industries'
'Bolo App'
'BolRealty'
'Bombay Shaving Company'
'Bombay Shirt Company'
'Bona Vita'
'Bonhomia'
'Bonphulapl'
'Book My Diamond'
'Book My Show'
'Book Servicing'
'BookEventz'
'BookMeIn'
'BookMyBai'
'BookMyShow'
'Bottr.me'
'Bounce'
'Bounty App'
'Box My Space'
'Box8'
'Boxmyspace'
'Boxx.ai'
'Brick2Wall'
'BRIDGEi2I'
'Brigge'
'Briston Technomach'
'Bro4U'
'BroEx'
'Broomberg'
'Browntape'
'BrowserStack'
'Bucker'
'Buddy'
'Buddy4studdy'
'Bueno'
'Buildkar'
'BuildSupply'
'BuildTraders'
'Buildzar'
'Bumper'
'Burger Singh'
'Buttercups'
'Butterfly Interactive'
'BuyHatke'
'Byg'
"Byju's"
'Cabsguru'
'Cakart'
'Call Health'
'Campus Diaries'
'CanvasFlip'
'Canvera'
'Canvs'
'Capabiliti'
'Capillary'
'Capillary Tech'
'Capita World'
'Capital Float'
'Capricoast'
'Capzest'
'Caratlane'
'Caravan Craft'
'Caravan Craft Retail'
'Carcrew'
'CarDekho'
'Care24'
'Career Anna'
'Career360'
'CareonGO'
'Careongo'
'Carls Jr'
'CaRPM'
'Cars24'
'Cartisan'
'Cartrade'
'CarTrade'
'CarveNiche'
'Casa2inns'
'Cash Suvidha'
'Cashe'
'Cashflo'
'CashFree'
'Cashify'
'Cashkaro'
'Cashkumar'
'Cbrex'
'Cbs'
'CCAvenue'
'CCavenue'
'Celerix'
'Celes Care'
'Cerebroz'
'Chaayos'
'Chai Point'
'Chai Thela'
'ChaiPoint'
'Chakr Innovation'
'Changer Mints'
'Chargebee'
'ChargeBee'
'Chargein'
'ChatOnGo'
'CheersOye!'
'Chefs Basket'
'Chevon'
'Chikoop'
'Chillr'
'ChipperSage'
'Chloroplast Foods'
'ChqBook'
'Chrysalis'
'Chumbak'
'Chymera VR'
'CimplyFive'
'Citrus Payment'
'CityFlo'
'CityFurnish'
'CityShor'
'Civilsdaily'
'Clapsnslaps'
'CleanseCar'
'ClearDekho'
'ClearTax'
'Cleartax'
'Cleartrip'
'CleverSharks'
'CleverTap'
'Click2Clinic'
'Clip App'
'Clodura'
'Clonect Solutions'
'Cloud Lending'
'Cloudacar'
'CloudCherry'
'Cloudcherry Analytics'
'CloudLabs'
'CloudPay'
'Cloudrino'
'CloudSolutions'
'CloudSolutions_576'
'CloudSolutions_682'
'Clovia'
'Clumio'
'Co Life'
'Codemojo'
'CodingLabs'
'CoinTribe'
'CollateBox'
'Collateral Medical'
'Collectabillia'
'CollegeDekho'
'CollegeDunia'
'CollPoll'
'Comarete'
'Commeasure'
'Commonfloor'
'Commut'
'ConfirmTKT'
'ConfirmtTkt'
'Connaizen'
'Connect India'
'ConnectAbank'
'Consure Medical'
'Convegenius'
'Cooey'
'Cookaroo'
'Cookifi'
'Coolshare'
'Coppre'
'CoreConnect'
'CoreConnect_1085'
'CoreFlow'
'CoreSpace'
'Corporate360'
'Corseco'
'Couponmachine'
'CouponRaja'
'CoutLoot'
'Coutloot'
'CoveIoT'
'Coverfox'
'CoverFox'
'Craftstvilla'
'Craftsvilla'
'CraftsVilla'
'Crayon Data'
'Creators Gurukul'
'Cred'
'Credifiable'
'CrediHealth'
'Credihealth'
'Credit Mate'
'Credit Sudhaar'
'Credit Vidya'
'CreditMantri'
'CreditMate'
'CreditSeva'
'CreditVidya'
'CredR'
'Credright'
'Credy'
'Creo'
'CroFarm'
'Crofarm'
'CRON Systems'
'Cropin'
'CropIn'
'Crossahead'
'Crowdera'
'Crowdfire'
'Crown-it'
'CrownIt'
'Crownit'
'Cube Consumer Services'
'Cube26'
'Cuberoot'
'Cubito'
'Cuelearn'
'CueMath'
'Cult'
'Cult Fitness'
'Culture Machine'
'CultureAlley'
'Cupick'
'CupoNation'
'Curatio'
'Cure Fit'
'CureFit'
'Curefit'
'CureInstant'
'CureJoy'
'Curie Labs'
'Curiositi'
'Curofy'
'Customer360'
'CustomerSucessBox'
'Customfurnish'
'CustomFurnish'
'Cyclops'
'CyclopsMedtech'
'Cygnus Hospitals'
'Daaki'
'Daalchini Technologies'
'Daily hunt'
'Daily Ninja'
'Daily Rounds'
'Dailyhunt'
'DailyHunt'
'DailyNinja'
'DailyObjects'
'DailyRounds'
'DarwinBox'
'Data Resolve'
'DataAnalytics'
'DataAnalytics_423'
'DataEdge'
'DataHive'
'DataWeave'
'DawaiLelo'
'DayBox'
'Dazo'
'Deal 4Loans'
'Deal Street Asia'
'Deal4Loans'
'Dealwithus'
'deGustibus'
'Dekkho'
'Delhivery'
'Delight Foods'
'Demyto'
'Derbii'
'Design Cafe'
'DesignBids'
'Devourin'
'Deyor Camps'
'Deyor Rooms'
'Dhruva'
'Dhruva Space'
'DiabetOmics'
'Didi'
'Digiconectt'
'Digilend'
'Digio'
'Digit'
'Digital F5'
'Digital Gorkha'
'Digital Mall Asia'
'Dil Mil'
'Dipper'
'Direct Create'
'Diro Labs'
'DishCo'
'Dishq'
'Disprz'
'Djubo'
'DocPlexus'
'DocsApp'
'DocTalk'
'Doctor Insta'
'DoctorInsta'
'DogSpot'
'Don Scratch Your Head'
'DoneThing'
'DoodhWala'
'Doormint'
'DoSelect'
'Doxper'
'Dream Wallets'
'Dream11'
'Drip capital'
'DriveEdge'
'DriveEdge_29'
'DriveFit'
'DriveFit_560'
'DriveLoop'
'DriversCart'
'DriveSkool'
'Drivestream'
'DriveU'
'Drivezy'
'Drivify'
'DrivoJoy'
'Droom'
'Dropkaffe'
'DropKaffe'
'Drums Food'
'Druva'
'Duffl'
'Dunzo'
'Early Salary'
'EarlySalary'
'Earth Food'
'Easy Diner'
'EasyEcom'
'EasyFix'
'EasyGov'
'EasyKhaana'
'EasyPolicy'
'Easypolicy'
'EasyRewardz'
'EasyRoads'
'Eat.Shop.Love'
'Eatfresh'
'Eatlo'
'Eatonomist'
'Eattreatonline'
'Eazy Coach'
'EazyDiner'
'eBikeGo'
'Eckovation'
'Ecolibriumenergy'
'Ecom Express'
'Ecozen'
'Edelweiss'
'EdgeFx'
'EdTechReview'
'Edu4Share'
'EduAce Services'
'EduBox'
'EduBox_144'
'EduBridge'
'EduKart'
'EduMart'
'EduMart_176'
'EduPristine'
'Edureka'
'Edurev'
'EduRev'
'EduTech'
'Edyoo'
'eKincare'
'Elanic'
'ElasticRun'
'ElastiRun'
'ElderAid Wellness'
'Elemential'
'Elong'
'Elucidata'
'Emflux Motors'
'Emiza'
'Emojifi'
'Enabli'
'Enakshi'
'enCashea'
'Endless Robotics'
'Engineer.ai'
'EngineerBabu'
'Englishleap'
'enKast'
'Entropik'
'Entropika'
'Entropy Innovations'
'Envoged'
'ePathsala'
'EPayLater'
'Epiq Capital'
'ePoise'
'Eps'
'eQuickies'
'Era'
'Eruditus'
'eSadar'
'eSahai'
'Eshakti'
'eShakti'
'eShiksha'
'eSwasthya'
'Etaout'
'Ethinos'
'Ethosh'
'EureQa'
'EvenGini'
'EveningFlavors'
'Events High'
'Evibe'
'Explara'
'Explore Life traveling'
'ExtraaEdge'
'ExtraCarbon'
'Eywa Media'
'EzCred'
'Ezetap'
'Ezyhaul'
'EzySolare'
'Ezytruk'
'Faasos'
'Faaya'
'Fab Hotels'
'FabAlley'
'FabHotels'
'FableStreet'
'Fabogo'
'Fabulyst'
'FabX'
'Faircent'
'FalconBrick'
'Fame'
'FarEye'
'Farm Taaza'
'FarMart'
'FarmBox'
'FarmFit'
'FarmFit_840'
'Farmizen'
'FarmLink'
'FarmTech'
'Fashalot'
'Fashionablyin'
'Fashionove'
'Fashor'
'FastFox'
'Fastudent'
'FeetApart'
'Fieldassist'
'Finance Buddha'
'Fincash'
'Find My Stay'
'FindmeaShoe'
'Findow'
'FindUrClass'
'Findyahan'
'FindYahan'
'FinFoods'
'FinFoods_1034'
'FinFoods_246'
'FinFoods_744'
'Fingerlix'
'Finomena'
'Finova Capital'
'FinSense'
'FinSense_162'
'FinSpace'
'Fintellix'
'Fintobox'
'Finzy'
'First Eat'
'First Moms Club'
'FirstCry'
'FirstTouch'
'Fisdom'
'Fitcircle'
'Fitmein'
'FitMeIn'
'Fitnapp'
'Fitpass'
'FiTraQ'
'Fitraq'
'Fitso'
'Fitternity'
'Five Star Group'
'FixNix'
'Fixy'
'Flashdoor'
'Flatchat'
'FlatFurnish'
'Flatpebble'
'FleetRover'
'FleetX'
'Flexiloans'
'Flexing It'
'FlickBay'
'Flickstree'
'FlipClass'
'Flipkart'
'Flixy Games'
'Flocareer'
'Flochat'
'Flutura'
'Flyrobe'
'Flytxt'
'Focus Digit'
'FoodAbhi'
'FoodFit'
'FoodLoop'
'Foodmemories'
'Foodpanda'
'FoodSolutions'
'FoodTalkIndia'
'Footprints Education'
'ForeverShop'
'Formcept'
'Fourseven'
'Fourth Ambit'
'Fourth Partner Energy'
'Foyr'
'FPL Technologies'
'Fr8'
'Fracktal Works'
'Fractal Analytics'
'Frankly'
'Frapperz'
'FreeCharge'
'Freedom Smart Labs'
'Fresh Food Concepts'
'FreshBox'
'FreshBoxx'
'Freshboxx'
'FreshDesk'
'Freshdesk'
'Freshee'
'FreshMenu'
'Freshmonk'
'FreshSolutions'
'FreshSolutions_178'
'FreshTech'
'FreshTech_329'
'FreshTech_651'
'FreshToHome'
'FreshVnF'
'Freshworks'
'FreshWorld'
'Front Desk AI'
'FroyoFit'
'Frsh'
'Frsh.co'
'Ftcash'
'FTCash'
'Fulfil.IO'
'Funcart'
'Funcastic'
'Fundamentor'
'FundsIndia'
'FunOnGo'
'Furdo'
'Furlenco'
'Furtados School of Music'
'Fusion Microfinance'
'Fxkart'
'FXMartIndia'
'Fyle'
'Fyle Technologies'
'Fynd'
'Fyne'
'Fyre'
'Gaana'
'Gadgets 360'
'Gadgetwood'
'Gajty'
'Galleri5'
'Gameezop'
'GameXS'
'GameZop'
'Gaming Monk'
'Gamooz'
'Gapoon'
'Garage On Road'
'Gear6'
'Genextstudents'
'Genie'
'Genius Corner'
'GenNext Students'
'Get My Parking'
'Get Simpl'
'GetFocus'
'GetMyPeon'
'getNow'
'GetVee'
'Gibbs'
'Gibss'
'Giftxoxo'
'GigIndia'
'Gingercrush'
'Girnar Software'
'Glam Studios'
'Glamrs'
'GlamStudios'
'Glassic'
'GlowRoad'
'Glowroad'
'Glowship'
'Goalwise'
'Gobolt'
'GoBumpr'
'GoChoppers'
'GoComet'
'GoDesi'
'Godof Hospitals'
'GoFro'
'GoFynd'
'GoGo Truck'
'GoJavas'
'GoldFarm'
'GolfLAN'
'Gomalon'
'GoMechanic'
'Good Methods Global'
'Goodbox'
'Goodera'
'Goodservice'
'Goomo'
'GoPigeon'
'GOQii'
'GoQii'
'Goqii'
'goSporto'
'GoYaNo'
'GoZefo'
'Gozoomo'
'Grab'
'Grabhouse'
'GrabOnRent'
'Gradopedia'
'GramCover'
'Gramophone'
'GrandOpinion'
'Graphene'
'Graphic India'
'Gray Routes'
'GreenConnect'
'GreenConnect_630'
'GreenEdge'
'Greenlight Planet'
'GreenMart'
'Grex'
'Grey Campus'
'Grey Orange'
'GreyAtom'
'GreytHR'
'Gridle'
'Grofers'
'Groupon India'
'Grover Zampa'
'Grow Fit'
'GrowFitter'
'GrowthCare'
'GrowthConnect'
'GrowthFlow'
'Groww'
'Guarented'
'Guiddoo'
'Guidoo'
'GuruG Learning'
'Gurukul'
'Gyaanzone'
'GyanDhan'
'Gympik'
'GymTrekker'
'HackerEarth'
'HackerRank'
'HalaPlay'
'HandyHome'
'HandyTrain'
'Hansa Customer Equity'
'Hansel io'
'Hansel.io'
'Happay'
'Happily Unmarried'
'HappilyUnmarried'
'Happitoo'
'Happy EMI'
'Happy2Refer'
'Happydemic'
'HappyGoEasy'
'Haptik'
'Haqdarshak'
'Harness Handitouch'
'HashLearn'
'HashTaag'
'Hasura'
'HeadOut'
'Heads Up For Tails'
'HEAL Institute'
'Healers At Home'
'HealthAnalytics'
'HealthAnalytics_1095'
'HealthAssure'
'Healthbuds'
'HealthCare'
'Healthcare at Home'
'HealthEminds'
'HealthEnablr'
'HealthFin'
'Healthi'
'Healthians'
'HealthifyMe'
'Healthifyme'
'HealthIntel'
'HealthKart'
'HealthKumbh'
'HealthMir'
'HealthRise'
'Healthsignz'
'HealthSutra'
'HealthWorks'
'HealthWorks_839'
'HealthyWorld'
'Heckyl'
'Hello Curry'
'Hello Tax'
'HelpChat'
'Helpi'
'HelpShift'
'Heterogenous'
'Hevo Data'
'HeyBiz'
'HeyPillow'
'High Radius'
'HighRadius'
'Highway Delite'
'HiJinny'
'Hike'
'Hike Messenger'
'HipBar'
'Hipcask'
'HipCouch'
'Hippily'
'Hipship'
'HitGrit'
'Hitwicket'
'HolaChef'
'HolidayIQ'
'Holidify'
'Holisol Logistics'
'HomeAnalytics'
'HomeCapital'
'HomeFoods'
'HomeLane'
'HomeMart'
'HomeMart_208'
'Homergize'
'Homers'
'HomeStudio'
'Hoopy'
'Hopping Chef'
'Hoppingo'
'Hopscotch'
'Horntell'
'Hostel Dunia'
'Hotelogix'
'Hotify'
'House of Msasaba'
'Housejoy'
'Housing'
'HousingMan'
'Houssup'
'Howdy Ventures'
'Hubilo'
'HUG Innovations'
'Hugefly'
'Hungama'
'HungerBox'
'Hungry Foal'
'HWell24'
'HWell24 Plus'
'HyperLabs'
'HyperLoop'
'HyperLoop_850'
'Hypernova Interactive'
'HyperSpace'
'HyperSpace_791'
'HyperTrack'
'HyperVerge'
'I Can Stay'
'I-Lend'
'I2e1'
'i2i Funding'
'I2ifunding'
'I3sysytems'
'Iamwire'
'iAugmentor Labs'
'IBSFintech'
'iBus Networks'
'Icertis'
'iChef'
'Ichr'
'iCliniq'
'iCrushiFlush'
'iCustomadeit'
'ICustomMadeIt'
'Idea Bubbles'
'IdeaChakki'
'IdeaForge'
'Ideal Insurance'
'IDfy'
'IDG Ventures'
'iDreamCareer'
'IFMR Holdings'
'iGenetics'
'Ignis Careers'
'Igp'
'iGrenEnergi'
'IIM Jobs'
'ImageProVision'
'Imaginate'
'iManageMyHotel'
'Imarticus Learning'
'IMAX Program'
'IMbesharam'
'Imedilane'
'iMMi Life'
'Impact Analytics'
'ImpactGuru'
'Impartus'
'Inayo'
'Inc42'
'Inclov'
'InCred'
'InCred Finance'
'Increff'
'Indee'
'Indi'
'India Gifts Portal'
'IndiaLends'
'Indiamart'
'IndianRoots'
'Indiez'
'Indifi'
'IndigoLearn'
'Indix'
'Indofash'
'Indus OS'
'IndustryBuying'
'INDwealth'
'Infeedo'
'Infibeam'
'Infinite Analytics'
'Infinity Assurance'
'Infisecure'
'Infogain'
'Infoworks'
'Infurnia'
'iNICU'
'Ink Monk'
'InkMonk'
'InMobi'
'inMotion'
'Innefu Security Consulting'
'Inner Hour'
'InnerChef'
'InnoNano Research'
'Innoplexus'
'Innov8'
'Innovaccer'
'Innovapptive'
'Innoviti'
'Inshorts'
'Insider'
'Inspirock'
'InstaBounce'
'Instacar'
'InstaLively'
'InstantPay'
'InstaOffice'
'Instaproc'
'InstaSafe'
'Instavans'
'Intelligence Node'
'IntelligenceNODE'
'Intelligent Interfaces'
'Interviewpad'
'Intgrea'
'Inthree'
'Intouchapp'
'Intruo'
'Intuit Things'
'iNurture'
'Inuxu'
'Invictus Oncology'
'ION Energy'
'iOrderFresh'
'IOTrek'
'Iqlect'
'IQlect'
'iServe Financial'
'iService'
'Isfc'
'iSTAR'
'iStar Skill Development'
'iStyleYou'
'Ithaka'
'iTraveller'
'Itzcash'
'Ixigo'
'iZofy'
'Jay Robotix'
'Jaypore'
'Jazzmyride'
'JetSetGo'
'Jhakaas'
'Jiffstore'
'Jigsaw Academy'
'Jivox'
'Jiyo Natural'
'Jobick'
'Jobspire'
'JoeHukum'
'Johari Shop'
'Jolly Food Fellow'
'Jombay'
'Joolz'
'Josh Talks'
'JoulestoWatts'
'Joy by nature'
'Juggernaut'
'Jugnoo'
'Julia Computing'
'JumboBasket'
'Jumbotail'
'Juno Clinic'
'Juspay'
'Jusride'
'Just Buy Live'
'Justbooks'
'Justdakhila'
'JustDoc'
'JustLikeNew'
'JustRide'
'KAARYAH'
'KabadiExpress'
'Kabadiwala'
'Kalaage'
'Kaleidofin'
'Kalpnik Technologies'
'Kanhaiya'
'Karma Healthcare'
'Karma Recycling'
'KarmaCircles'
'Karomi'
'Kartrocket'
'Kashmir Box'
'KeepTrax'
'Ketchupp'
'Ketto'
'KhanaGadi'
'Khel Now'
'Kickstart Jobs'
'Kidovators'
'Kidsstoppress'
'Kinara Capital'
'Kinsane Entertainment'
'Kissht'
'Kleeto'
'KleverKid'
'Klinic App'
'Klip'
'Kloseby'
'Klozee'
'KNAB Finance'
'Knit'
'Knolskae'
'Knowlarity'
'Kobster'
'Kochi Post'
'Kolabro'
'Konsult App'
'KOOH Sports'
'Koovs'
'Korra'
'KountMoney'
'Kratikal'
'KrazyBee'
'Kreate Konnect'
'KredX'
'Kriger Campus'
'Kuants'
'Kulzy'
'Kuvera'
'kWatt Solutions'
'Kyazoonga'
'La Renon'
'LabInApp'
'LabsAdvisor'
'LabStreet'
'LafaLafa'
'LatestOne'
'LaundryAnna'
'Lavelle Networks'
'Lawrato'
'LazyLad'
'Leadburg'
'Leaf'
'Leaf Wearables'
'Leap India'
'Leaping Caravan'
'LearnOn'
'LearnTron'
'Leegality'
'Leena AI'
'Legal Raasta'
'LegalRaasta'
'Legistify'
'Lehlehsports'
'LenDenClub'
'Lendingkart'
'Lenskart'
'LensKart'
'LensPick'
'Leopetra'
"Let's Barter"
'LetReach'
'Lets'
'Lets Endorse'
'Lets Reap'
'LetsMD'
'Letsservice'
'LetsTransport'
'LetsVenture'
'Leverage Edu'
'LexComply'
'Liases Foras'
'Licious'
'LifCare'
'Life Circle'
'Life in Control'
'Liftiee'
'LiftO'
'Lime Tray'
'LimeRoad'
'Limo'
'Liqvid'
'ListUp'
'Little'
'Little Black Book'
'Little Black Book Delhi'
'Littlemore'
'Livehealth'
'LiveNutriFit'
'Living Local'
'LivSpace'
'Lo! Foods'
'Loadshare'
'Loan Frame'
'LoanBaba'
'LoanCircle'
'Loanmeet'
'LoanTap'
'LoanZen'
'Localbanya'
'LocalCircles'
'LocalOye'
'LocalRamu'
'Locanix'
'Locus'
'Log9 Materials'
'Logic Roots'
'LogicRoots'
'LogiMart'
'LogiMart_960'
'LogiNext'
'LogiRise'
'LogiSense'
'Lollypop'
'LookAtMe'
'Lookup'
'LoudShout'
'LoveCycles'
'LoyaltyPrime'
'Loylty Rewards'
'Lucideus'
'Lumiere'
'Luxuryhues'
'Lybrate'
'M-Taxi'
'M.paani'
'MaalGaadi'
'MaaxMarket'
'MachaDalo'
'Mad Street Den'
'MadRat Games'
'Magic Crate'
'MagicBricks'
'Magicpin'
'MagicX'
'Mahindra First Choice'
'MakeMyTrip'
'Makkajai'
'Mamaearth'
'Mamagoto'
'ManageMySpa'
'Manch'
'Manthan'
'MapMyGenome'
'Maptags'
'MarianaIQ'
'Markets and Markets'
'Massblurb'
'Math Buddy'
'Matrubharti'
'MaxMyWealth'
'Maya'
'Mazkara'
'MCaffeine'
'mChamp'
'MealHopper'
'MebelKart'
'Mech Mocha'
'Medd'
'medECUBE'
'MedGenome'
'Medidaili'
'MediHive'
'MediHive_1008'
'Medikabazaar'
'Medikoe'
'Medinfi'
'MediSpace'
'MediSpace_1029'
'MediWorks'
'Medlife'
'MedTel'
'Medwell Ventures'
'Medzin'
'Meesho'
'MeetUniv'
'Melorra'
'MEngage'
'MeraDoctor'
'MeraKisan'
'MergerWare'
'Meritnation'
'Meru Cabs'
'MessaGif'
'Metro Bikes'
'mFicient'
'MFine'
'Mihup'
'Mihuru'
'Milkbasket'
'Milofy'
'Mind Your Fleet'
'Mindler'
'MindTickle'
'MindYourFleet'
'Minjar'
'Mintifi'
'MintM'
'Mintwalk'
'Mishry Reviews'
'mishTag'
'MiStay'
'Misters'
'MobiDent'
'MobieFit'
'Mobikon'
'MobiKwik'
'Mobile Premier League'
'Mobiliz AR'
'MObiquest'
'Mobycy'
'MockBank'
'MoEngage'
'Moglix'
'Mojarto'
'MoMagic'
'MoMark'
'Momoe'
'MoneyOnMobile'
'MoneyTap'
'MonkeyBox'
'Monsoon Fintech'
'Moodoo'
'MoonFrog Labs'
'Moong Labs'
'Moovo'
'Mosambee'
'MotoMojo'
'mPaani'
'Mr Hot Foods'
'MrNeeds'
'Mse'
'mShipper'
'MSM Box'
'mSwipe'
'Mubble'
'MuhurtMaza'
'Multibhashi'
'Multiplier Solutions'
'Murgency'
'Muvizz'
'My Forex Eye'
'My Healthcare'
'My OmNamo'
'MyAdvo'
'MyCFO'
'MyChild App'
'MyCity4Kids'
'MyCuteOffice'
'MyDentist'
'MyDentistChoice'
'MyDermacy'
'MyDidi'
'MyDreamStore'
'Myeglu'
'Myelin Foundry'
'MyGlamm'
'MyGreens'
'MyGubbi'
'MyIndianStay'
'MyKindofJob'
'MyLoanCare'
'Myly'
'MyNoticePeriod'
'Myntra'
'Myonsto'
'MyPetrolPump'
'MyPoolin'
'Myra'
'MySeniorDoctor'
'MySmartPrice'
'Mystifly'
'MySUN'
'MySuperBrain'
'MyTaxiIndia'
'MyUpchar'
'N.o.w'
'Naaptol'
'Nactus'
'Nagpur Wholesale'
'NanoClean Global'
'Narvar'
'Native Special'
'Naturally Yours'
'NatureNama'
'Navia Life Care'
'Nayi Disha'
'Nazara Technologies'
'NDTV ecommerce venture'
'NDTV Wedding portal'
'Near'
'NearBuy'
'NearFox'
'NearU'
'NeoGrowth'
'NeoGrowth Credit'
'NeoLabs'
'NeoLabs_1063'
'NeoLabs_65'
'NeoLabs_904'
'NeoSense'
'NeoSense_1062'
'NeoSense_564'
'NeoStencil'
'NeoTech'
'Neotrade Analytics'
'Nest Education'
'NestAway'
'NetLinx'
'NetMeds'
'Netree'
'Network Intelligence'
'NeuroEquilibrium'
'NeuroSynaptic'
'New Castle Technologies'
'Newgen Payments'
'Newgen Software'
'NewsDistill'
'NewsHunt'
'NewsInShorts'
'NewsLaundry'
'Newspatrolling'
'NextFlow'
'NextGen'
'NextSense'
'NextSense_10'
'NextSense_395'
'NextStack'
'Niffler'
'NightStay'
'Niki.ai'
'Nimble Wireless'
'NimbusLabs'
'NimbusLabs_243'
'NimbusLabs_846'
'NimbusMart'
'NimbusWorks'
'Ninjacart'
'Niramai'
'NirogStreet'
'Nivesh'
'NiYO Solutions'
'NoBroker'
'Noddapp'
'Noodle Play'
'NoPaperForms'
'Northmist'
'Notary Mama'
'Notesgen'
'Noticeboard'
'Notion Press'
'NowFloats'
'Nudgespot'
'Nukkad Shops'
'NumberMall'
'Numberz'
'Numeroseven'
'Nurturey'
'Nuvepro'
'NxtGen'
'Nykaa'
'Obino'
'Observe AI'
'Octo.ai'
'OfBusiness'
'Oglas'
'Oho Shop'
'Oi Media'
'Oibanit'
'OkCredit'
'Ola'
'Ola Electric'
'Oliveboard'
'Olly Credit'
'Omnia Information'
'Omnify'
'Omnikart'
'OncoStem'
'One Labs'
'OneAssist'
'OneClickWash'
'OneStepUp'
'Oneway.cab'
'OnlineRTI'
'OnlineTyari'
'ONN Bikes'
'Onspoon'
'Oorjan'

In [85]:
# funding.to_csv("Cleaned Startup funding.csv", index=False)